/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var a=this||self,b=function(f,k){f=f.split(".");var e=a;f[0]in e||"undefined"==typeof e.execScript||e.execScript("var "+f[0]);for(var g;f.length&&(g=f.shift());)f.length||void 0===k?e=e[g]&&e[g]!==Object.prototype[g]?e[g]:e[g]={}:e[g]=k};var c={c:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},b:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}},d=c;d=c;var h={ga:"y",oa:"y G",ha:"MMM y",ia:"MMMM y",pa:"MM/y",G:"MMM d",H:"MMMM dd",J:"M/d",I:"MMMM d",ma:"MMM d, y",ea:"EEE, MMM d",na:"EEE, MMM d, y",i:"d",la:"MMM d, h:mm a zzzz"},l=h;l=h;var m={s:["BC","AD"],o:["Before Christ","Anno Domini"],L:"JFMAMJJASOND".split(""),Y:"JFMAMJJASOND".split(""),F:"January February March April May June July August September October November December".split(" "),X:"January February March April May June July August September October November December".split(" "),U:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),$:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),da:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
ba:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),W:"Sun Mon Tue Wed Thu Fri Sat".split(" "),aa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),M:"SMTWTFS".split(""),Z:"SMTWTFS".split(""),V:["Q1","Q2","Q3","Q4"],S:["1st quarter","2nd quarter","3rd quarter","4th quarter"],a:["AM","PM"],g:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],ca:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],h:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],v:6,fa:[5,6],A:5},n=m;n=m;var p={l:".",B:",",N:"%",ka:"0",R:"+",D:"-",u:"E",P:"\u2030",C:"\u221e",K:"NaN",j:"#,##0.###",T:"#E0",O:"#,##0%",f:"\u00a4#,##0.00",m:"USD"},q=p;q=p;b("I18N_DATETIMESYMBOLS_ERAS",n.s);b("I18N_DATETIMESYMBOLS_ERANAMES",n.o);b("I18N_DATETIMESYMBOLS_NARROWMONTHS",n.L);b("I18N_DATETIMESYMBOLS_STANDALONENARROWMONTHS",n.Y);b("I18N_DATETIMESYMBOLS_MONTHS",n.F);b("I18N_DATETIMESYMBOLS_STANDALONEMONTHS",n.X);b("I18N_DATETIMESYMBOLS_SHORTMONTHS",n.U);b("I18N_DATETIMESYMBOLS_STANDALONESHORTMONTHS",n.$);b("I18N_DATETIMESYMBOLS_WEEKDAYS",n.da);b("I18N_DATETIMESYMBOLS_STANDALONEWEEKDAYS",n.ba);b("I18N_DATETIMESYMBOLS_SHORTWEEKDAYS",n.W);
b("I18N_DATETIMESYMBOLS_STANDALONESHORTWEEKDAYS",n.aa);b("I18N_DATETIMESYMBOLS_NARROWWEEKDAYS",n.M);b("I18N_DATETIMESYMBOLS_STANDALONENARROWWEEKDAYS",n.Z);b("I18N_DATETIMESYMBOLS_SHORTQUARTERS",n.V);b("I18N_DATETIMESYMBOLS_QUARTERS",n.S);b("I18N_DATETIMESYMBOLS_AMPMS",n.a);b("I18N_DATETIMESYMBOLS_DATEFORMATS",n.g);b("I18N_DATETIMESYMBOLS_TIMEFORMATS",n.ca);b("I18N_DATETIMESYMBOLS_DATETIMEFORMATS",n.h);b("I18N_DATETIMESYMBOLS_FIRSTDAYOFWEEK",n.v);b("I18N_DATETIMESYMBOLS_WEEKENDRANGE",n.fa);
b("I18N_DATETIMESYMBOLS_FIRSTWEEKCUTOFFDAY",n.A);b("I18N_DATETIMEPATTERNS_YEAR_FULL",l.ga);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_ABBR",l.ha);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_FULL",l.ia);b("I18N_DATETIMEPATTERNS_MONTH_DAY_ABBR",l.G);b("I18N_DATETIMEPATTERNS_MONTH_DAY_FULL",l.H);b("I18N_DATETIMEPATTERNS_MONTH_DAY_SHORT",l.J);b("I18N_DATETIMEPATTERNS_MONTH_DAY_MEDIUM",l.I);b("I18N_DATETIMEPATTERNS_WEEKDAY_MONTH_DAY_MEDIUM",l.ea);b("I18N_DATETIMEPATTERNS_DAY_ABBR",l.i);
void 0!==n.ja&&b("I18N_DATETIMESYMBOLS_ZERODIGIT",n.ja);b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_SEP",q.l);b("I18N_NUMBERFORMATSYMBOLS_GROUP_SEP",q.B);b("I18N_NUMBERFORMATSYMBOLS_PERCENT",q.N);b("I18N_NUMBERFORMATSYMBOLS_ZERO_DIGIT",q.ka);b("I18N_NUMBERFORMATSYMBOLS_PLUS_SIGN",q.R);b("I18N_NUMBERFORMATSYMBOLS_MINUS_SIGN",q.D);b("I18N_NUMBERFORMATSYMBOLS_EXP_SYMBOL",q.u);b("I18N_NUMBERFORMATSYMBOLS_PERMILL",q.P);b("I18N_NUMBERFORMATSYMBOLS_INFINITY",q.C);b("I18N_NUMBERFORMATSYMBOLS_NAN",q.K);
b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_PATTERN",q.j);b("I18N_NUMBERFORMATSYMBOLS_SCIENTIFIC_PATTERN",q.T);b("I18N_NUMBERFORMATSYMBOLS_PERCENT_PATTERN",q.O);b("I18N_NUMBERFORMATSYMBOLS_CURRENCY_PATTERN",q.f);b("I18N_NUMBERFORMATSYMBOLS_DEF_CURRENCY_CODE",q.m);b("I18N_COMPACT_DECIMAL_SHORT_PATTERN",d.c);b("I18N_COMPACT_DECIMAL_LONG_PATTERN",d.b);
