/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var a=this||self,b=function(f,k){f=f.split(".");var e=a;f[0]in e||"undefined"==typeof e.execScript||e.execScript("var "+f[0]);for(var g;f.length&&(g=f.shift());)f.length||void 0===k?e=e[g]&&e[g]!==Object.prototype[g]?e[g]:e[g]={}:e[g]=k};var c={ja:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},ia:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}},d=c;d=c;var h={ea:"y",na:"y G",fa:"MMM y",ga:"MMMM y",oa:"MM/y",D:"MMM d",F:"MMMM dd",H:"M/d",G:"MMMM d",la:"MMM d, y",ca:"EEE, MMM d",ma:"EEE, MMM d, y",g:"d",ka:"MMM d, h:mm a zzzz"};h={ea:"y",na:"y G",fa:"MMM y",ga:"MMMM y",oa:"MM/y",D:"d MMM",F:"dd MMMM",H:"dd/MM",G:"d MMMM",la:"d MMM y",ca:"EEE, d MMM",ma:"EEE, d MMM y",g:"d",ka:"d MMM, HH:mm zzzz"};var l={m:["BC","AD"],l:["Before Christ","Anno Domini"],J:"JFMAMJJASOND".split(""),W:"JFMAMJJASOND".split(""),C:"January February March April May June July August September October November December".split(" "),V:"January February March April May June July August September October November December".split(" "),S:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),Y:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ba:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
$:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),U:"Sun Mon Tue Wed Thu Fri Sat".split(" "),Z:"Sun Mon Tue Wed Thu Fri Sat".split(" "),K:"SMTWTFS".split(""),X:"SMTWTFS".split(""),T:["Q1","Q2","Q3","Q4"],P:["1st quarter","2nd quarter","3rd quarter","4th quarter"],a:["AM","PM"],c:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],aa:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],f:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],s:6,da:[5,6],u:5};
l={m:["BC","AD"],l:["Before Christ","Anno Domini"],J:"JFMAMJJASOND".split(""),W:"JFMAMJJASOND".split(""),C:"January February March April May June July August September October November December".split(" "),V:"January February March April May June July August September October November December".split(" "),S:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),Y:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ba:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
$:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),U:"Sun Mon Tue Wed Thu Fri Sat".split(" "),Z:"Sun Mon Tue Wed Thu Fri Sat".split(" "),K:"SMTWTFS".split(""),X:"SMTWTFS".split(""),T:["Q1","Q2","Q3","Q4"],P:["1st quarter","2nd quarter","3rd quarter","4th quarter"],a:["am","pm"],c:["EEEE, d MMMM y","d MMMM y","d MMM y","dd/MM/y"],aa:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],f:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],s:0,da:[5,6],u:3};var m={i:".",v:",",L:"%",ha:"0",O:"+",B:"-",o:"E",N:"\u2030",A:"\u221e",I:"NaN",h:"#,##0.###",R:"#E0",M:"#,##0%",b:"\u00a4#,##0.00",j:"USD"};m={i:".",v:",",L:"%",ha:"0",O:"+",B:"-",o:"E",N:"\u2030",A:"\u221e",I:"NaN",h:"#,##0.###",R:"#E0",M:"#,##0%",b:"\u00a4#,##0.00",j:"GBP"};b("I18N_DATETIMESYMBOLS_ERAS",l.m);b("I18N_DATETIMESYMBOLS_ERANAMES",l.l);b("I18N_DATETIMESYMBOLS_NARROWMONTHS",l.J);b("I18N_DATETIMESYMBOLS_STANDALONENARROWMONTHS",l.W);b("I18N_DATETIMESYMBOLS_MONTHS",l.C);b("I18N_DATETIMESYMBOLS_STANDALONEMONTHS",l.V);b("I18N_DATETIMESYMBOLS_SHORTMONTHS",l.S);b("I18N_DATETIMESYMBOLS_STANDALONESHORTMONTHS",l.Y);b("I18N_DATETIMESYMBOLS_WEEKDAYS",l.ba);b("I18N_DATETIMESYMBOLS_STANDALONEWEEKDAYS",l.$);b("I18N_DATETIMESYMBOLS_SHORTWEEKDAYS",l.U);
b("I18N_DATETIMESYMBOLS_STANDALONESHORTWEEKDAYS",l.Z);b("I18N_DATETIMESYMBOLS_NARROWWEEKDAYS",l.K);b("I18N_DATETIMESYMBOLS_STANDALONENARROWWEEKDAYS",l.X);b("I18N_DATETIMESYMBOLS_SHORTQUARTERS",l.T);b("I18N_DATETIMESYMBOLS_QUARTERS",l.P);b("I18N_DATETIMESYMBOLS_AMPMS",l.a);b("I18N_DATETIMESYMBOLS_DATEFORMATS",l.c);b("I18N_DATETIMESYMBOLS_TIMEFORMATS",l.aa);b("I18N_DATETIMESYMBOLS_DATETIMEFORMATS",l.f);b("I18N_DATETIMESYMBOLS_FIRSTDAYOFWEEK",l.s);b("I18N_DATETIMESYMBOLS_WEEKENDRANGE",l.da);
b("I18N_DATETIMESYMBOLS_FIRSTWEEKCUTOFFDAY",l.u);b("I18N_DATETIMEPATTERNS_YEAR_FULL",h.ea);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_ABBR",h.fa);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_FULL",h.ga);b("I18N_DATETIMEPATTERNS_MONTH_DAY_ABBR",h.D);b("I18N_DATETIMEPATTERNS_MONTH_DAY_FULL",h.F);b("I18N_DATETIMEPATTERNS_MONTH_DAY_SHORT",h.H);b("I18N_DATETIMEPATTERNS_MONTH_DAY_MEDIUM",h.G);b("I18N_DATETIMEPATTERNS_WEEKDAY_MONTH_DAY_MEDIUM",h.ca);b("I18N_DATETIMEPATTERNS_DAY_ABBR",h.g);
void 0!==l.pa&&b("I18N_DATETIMESYMBOLS_ZERODIGIT",l.pa);b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_SEP",m.i);b("I18N_NUMBERFORMATSYMBOLS_GROUP_SEP",m.v);b("I18N_NUMBERFORMATSYMBOLS_PERCENT",m.L);b("I18N_NUMBERFORMATSYMBOLS_ZERO_DIGIT",m.ha);b("I18N_NUMBERFORMATSYMBOLS_PLUS_SIGN",m.O);b("I18N_NUMBERFORMATSYMBOLS_MINUS_SIGN",m.B);b("I18N_NUMBERFORMATSYMBOLS_EXP_SYMBOL",m.o);b("I18N_NUMBERFORMATSYMBOLS_PERMILL",m.N);b("I18N_NUMBERFORMATSYMBOLS_INFINITY",m.A);b("I18N_NUMBERFORMATSYMBOLS_NAN",m.I);
b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_PATTERN",m.h);b("I18N_NUMBERFORMATSYMBOLS_SCIENTIFIC_PATTERN",m.R);b("I18N_NUMBERFORMATSYMBOLS_PERCENT_PATTERN",m.M);b("I18N_NUMBERFORMATSYMBOLS_CURRENCY_PATTERN",m.b);b("I18N_NUMBERFORMATSYMBOLS_DEF_CURRENCY_CODE",m.j);b("I18N_COMPACT_DECIMAL_SHORT_PATTERN",d.ja);b("I18N_COMPACT_DECIMAL_LONG_PATTERN",d.ia);
