#!/usr/bin/env bash

# Enable compton's fade-in effect so that the lockscreen gets a nice fade-in effect.

dbus-send --print-reply --dest=com.github.chjj.compton.${DISPLAY/:/_} / com.github.chjj.compton.opts_set string:no_fading_openclose boolean:false

# If disable unredir_if_possible is enabled in compton's config, we may need to disable that to avoid flickering. YMMV. To try that, uncomment the following line and the last two lines in this script.
# dbus-send --print-reply --dest=com.github.chjj.compton.${DISPLAY/:/_} / com.github.chjj.compton.opts_set string:unredir_if_possible boolean:false

# Suspend dunst and lock, then resume dunst when unlocked.
# pkill -u $USER -USR1 dunst

i3lock -n -i ~/Pictures/wallpaper.png --insidecolor=37344500 --ringcolor=ffffffff --line-uses-inside --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+960:y+540" --veriftext="" --wrongtext="" --greetertext="hello" --greetercolor=ffffffff --greeterpos="x+960:y+400" --ignore-empty-password --clock --wrongcolor=ffffffff --timecolor=ffffffff --timepos="x+1800:y+1000" --datecolor=ffffffff --datestr="%A, %d %B" --noinputtext="" --ring-width=10 --radius=70 --indicator --timestr="%I:%M %p"

# pkill -u $USER -USR2 dunst

# Revert compton's config changes.
sleep 0.2
dbus-send --print-reply --dest=com.github.chjj.compton.${DISPLAY/:/_} / com.github.chjj.compton.opts_set string:no_fading_openclose boolean:true

# dbus-send --print-reply --dest=com.github.chjj.compton.${DISPLAY/:/_} / com.github.chjj.compton.opts_set string:unredir_if_possible boolean:true

