"use strict";this.default_host=this.default_host||{};(function(_){var window=this;
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa,ba,ca,da,ea,fa,ja,pa;aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};da=ca(this);ea=function(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};
ea("Symbol",function(a){if(a)return a;var b=function(e,f){this.g=e;ba(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.g};var c=0,d=function(e){if(this instanceof d)throw new TypeError("b");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("c");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});fa=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
_.ha=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}};_.ia="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};if("function"==typeof Object.setPrototypeOf)ja=Object.setPrototypeOf;else{var la;a:{var ma={a:!0},na={};try{na.__proto__=ma;la=na.a;break a}catch(a){}la=!1}ja=la?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("d`"+a);return a}:null}_.oa=ja;
pa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
ea("WeakMap",function(a){function b(){}function c(k){var n=typeof k;return"object"===n&&null!==k||"function"===n}function d(k){if(!pa(k,f)){var n=new b;ba(k,f,{value:n})}}function e(k){var n=Object[k];n&&(Object[k]=function(t){if(t instanceof b)return t;Object.isExtensible(t)&&d(t);return n(t)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),n=Object.seal({}),t=new a([[k,2],[n,3]]);if(2!=t.get(k)||3!=t.get(n))return!1;t.delete(k);t.set(n,4);return!t.has(k)&&4==t.get(n)}catch(L){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,g=function(k){this.g=(h+=Math.random()+1).toString();if(k){k=_.ha(k);for(var n;!(n=k.next()).done;)n=n.value,this.set(n[0],n[1])}};g.prototype.set=function(k,n){if(!c(k))throw Error("g");d(k);if(!pa(k,f))throw Error("h`"+k);k[f][this.g]=n;return this};g.prototype.get=function(k){return c(k)&&pa(k,f)?k[f][this.g]:void 0};g.prototype.has=function(k){return c(k)&&pa(k,f)&&pa(k[f],this.g)};g.prototype.delete=function(k){return c(k)&&
pa(k,f)&&pa(k[f],this.g)?delete k[f][this.g]:!1};return g});
ea("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),k=new a(_.ha([[g,"s"]]));if("s"!=k.get(g)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var n=k.entries(),t=n.next();if(t.done||t.value[0]!=g||"s"!=t.value[1])return!1;t=n.next();return t.done||4!=t.value[0].x||"t"!=t.value[1]||!n.next().done?!1:!0}catch(L){return!1}}())return a;var b=new WeakMap,c=function(g){this.h={};this.g=
f();this.size=0;if(g){g=_.ha(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(g,k){g=0===g?0:g;var n=d(this,g);n.list||(n.list=this.h[n.id]=[]);n.entry?n.entry.value=k:(n.entry={next:this.g,previous:this.g.previous,head:this.g,key:g,value:k},n.list.push(n.entry),this.g.previous.next=n.entry,this.g.previous=n.entry,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.h[g.id],
g.entry.previous.next=g.entry.next,g.entry.next.previous=g.entry.previous,g.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.h={};this.g=this.g.previous=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).entry};c.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,
function(g){return g.value})};c.prototype.forEach=function(g,k){for(var n=this.entries(),t;!(t=n.next()).done;)t=t.value,g.call(k,t[1],t[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,k){var n=k&&typeof k;"object"==n||"function"==n?b.has(k)?n=b.get(k):(n=""+ ++h,b.set(k,n)):n="p_"+k;var t=g.h[n];if(t&&pa(g.h,n))for(g=0;g<t.length;g++){var L=t[g];if(k!==k&&L.key!==L.key||k===L.key)return{id:n,list:t,index:g,entry:L}}return{id:n,list:t,index:-1,entry:void 0}},e=function(g,
k){var n=g.g;return fa(function(){if(n){for(;n.head!=g.g;)n=n.previous;for(;n.next!=n.head;)return n=n.next,{done:!1,value:k(n)};n=null}return{done:!0,value:void 0}})},f=function(){var g={};return g.previous=g.next=g.head=g},h=0;return c});var qa=function(a,b){a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
ea("Array.prototype.keys",function(a){return a?a:function(){return qa(this,function(b){return b})}});ea("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});ea("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
ea("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("e`includes");if(b instanceof RegExp)throw new TypeError("f`includes");return-1!==this.indexOf(b,c||0)}});ea("Array.prototype.values",function(a){return a?a:function(){return qa(this,function(b,c){return c})}});_.ra=_.ra||{};_.m=this||self;_.sa="closure_uid_"+(1E9*Math.random()>>>0);_.ta=Date.now;

}catch(e){_._DumpException(e)}
try{
var xa,za,Aa,Ca,Da,Ga;_.p=function(a,b){a.prototype=(0,_.ia)(b.prototype);a.prototype.constructor=a;if(_.oa)(0,_.oa)(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.P=b.prototype};_.ua=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.va=function(a){a=a.split(".");for(var b=_.m,c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b};_.wa=function(){};
xa=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"};_.ya=function(a){var b=xa(a);return"array"==b||"object"==b&&"number"==typeof a.length};za=function(a){return"function"==xa(a)};Aa=0;_.Ba=function(a){return Object.prototype.hasOwnProperty.call(a,_.sa)&&a[_.sa]||(a[_.sa]=++Aa)};Ca=function(a,b,c){return a.call.apply(a.bind,arguments)};
Da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};_.q=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?_.q=Ca:_.q=Da;return _.q.apply(null,arguments)};
_.Ea=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};_.Fa=function(a,b){a=a.split(".");var c=_.m;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};_.r=function(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a};Ga=function(a){return a};
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.Ha=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Ha);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.r(_.Ha,Error);_.Ha.prototype.name="CustomError";
var Ia;Ia=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Ja=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,h=0;h<c;h++)if(h in f){var g=f[h];b.call(void 0,g,h,a)&&(d[e++]=g)}return d};_.Ka=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};
_.La=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};_.Na=function(a,b){b=_.Ma(a,b,void 0);return 0>b?null:"string"===typeof a?a.charAt(b):a[b]};_.Ma=function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};_.Oa=function(a,b){return 0<=Ia(a,b)};
_.Ra=function(a,b){b=Ia(a,b);var c;(c=0<=b)&&_.Pa(a,b);return c};_.Pa=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};_.Sa=function(a){return Array.prototype.concat.apply([],arguments)};_.Ta=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
var Va,Xa;_.Ua=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Va=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};_.Wa=function(a){var b={},c;for(c in a)b[c]=a[c];return b};Xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Ya=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Xa.length;f++)c=Xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
var Za;
_.$a=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;
var eb;_.ab=function(a,b){return 0==a.lastIndexOf(b,0)};_.bb=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.cb=function(a){return/^[\s\xa0]*$/.test(a)};_.db=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
_.fb=function(a,b){var c=0;a=(0,_.db)(String(a)).split(".");b=(0,_.db)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=eb(0==f[1].length?0:parseInt(f[1],10),0==h[1].length?0:parseInt(h[1],10))||eb(0==f[2].length,0==h[2].length)||eb(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c};
eb=function(a,b){return a<b?-1:a>b?1:0};
a:{var hb=_.m.navigator;if(hb){var ib=hb.userAgent;if(ib){_.gb=ib;break a}}_.gb=""}_.v=function(a){return-1!=_.gb.indexOf(a)};
_.jb=function(){return _.v("Trident")||_.v("MSIE")};_.kb=function(){return _.v("Firefox")||_.v("FxiOS")};_.mb=function(){return _.v("Safari")&&!(_.lb()||_.v("Coast")||_.v("Opera")||_.v("Edge")||_.v("Edg/")||_.v("OPR")||_.kb()||_.v("Silk")||_.v("Android"))};_.lb=function(){return(_.v("Chrome")||_.v("CriOS"))&&!_.v("Edge")};
var nb,rb;_.ob=function(){this.h="";this.j=nb;this.l=null};_.ob.prototype.pb=!0;_.ob.prototype.g=function(){return this.l};_.ob.prototype.Ia=!0;_.ob.prototype.Fa=function(){return this.h.toString()};_.pb=function(a){return a instanceof _.ob&&a.constructor===_.ob&&a.j===nb?a.h:"type_error:SafeHtml"};nb={};
_.qb=function(a,b){var c=new _.ob;if(void 0===Za){var d=null;var e=_.m.trustedTypes;if(e&&e.createPolicy){try{d=e.createPolicy("goog#html",{createHTML:Ga,createScript:Ga,createScriptURL:Ga})}catch(f){_.m.console&&_.m.console.error(f.message)}Za=d}else Za=d}d=Za;c.h=d?d.createHTML(a):a;c.l=b;return c};rb=new _.ob;rb.h=_.m.trustedTypes&&_.m.trustedTypes.emptyHTML?_.m.trustedTypes.emptyHTML:"";rb.l=0;_.sb=rb;_.tb=_.qb("<br>",0);
_.ub=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=_.pb(_.sb);return!b.parentElement});
var vb;vb=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.wb=function(a){return null==a?"":String(a)};
var xb,yb,Cb;xb=function(){return _.v("iPhone")&&!_.v("iPod")&&!_.v("iPad")};yb=function(){return xb()||_.v("iPad")||_.v("iPod")};_.zb=function(){return _.v("Macintosh")};_.Ab=function(){return _.v("Windows")};_.Bb=function(){return _.v("CrOS")};
Cb=function(){var a=_.gb,b="";_.Ab()?(b=/Windows (?:NT|Phone) ([0-9.]+)/,b=(a=b.exec(a))?a[1]:"0.0"):yb()?(b=/(?:iPhone|iPod|iPad|CPU)\s+OS\s+(\S+)/,b=(a=b.exec(a))&&a[1].replace(/_/g,".")):_.zb()?(b=/Mac OS X ([0-9_.]+)/,b=(a=b.exec(a))?a[1].replace(/_/g,"."):"10"):-1!=_.gb.toLowerCase().indexOf("kaios")?(b=/(?:KaiOS)\/(\S+)/i,b=(a=b.exec(a))&&a[1]):_.v("Android")?(b=/Android\s+([^\);]+)(\)|;)/,b=(a=b.exec(a))&&a[1]):_.Bb()&&(b=/(?:CrOS\s+(?:i686|x86_64)\s+([0-9.]+))/,b=(a=b.exec(a))&&a[1]);return b||
""};
var Db=function(a){Db[" "](a);return a};Db[" "]=_.wa;_.Eb=function(a,b,c){return Object.prototype.hasOwnProperty.call(a,b)?a[b]:a[b]=c(b)};
var Fb,Hb,Lb,Ob,Pb,Tb,Ub,Wb;Fb=_.v("Opera");_.Gb=_.jb();Hb=_.v("Edge");_.Ib=_.v("Gecko")&&!(-1!=_.gb.toLowerCase().indexOf("webkit")&&!_.v("Edge"))&&!(_.v("Trident")||_.v("MSIE"))&&!_.v("Edge");_.Jb=-1!=_.gb.toLowerCase().indexOf("webkit")&&!_.v("Edge");Lb=_.m.navigator||null;_.Kb=Lb&&Lb.platform||"";_.Mb=_.zb();_.Nb=_.Ab();Ob=function(){var a=_.m.document;return a?a.documentMode:void 0};
a:{var Qb="",Rb=function(){var a=_.gb;if(_.Ib)return/rv:([^\);]+)(\)|;)/.exec(a);if(Hb)return/Edge\/([\d\.]+)/.exec(a);if(_.Gb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Jb)return/WebKit\/(\S+)/.exec(a);if(Fb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Rb&&(Qb=Rb?Rb[1]:"");if(_.Gb){var Sb=Ob();if(null!=Sb&&Sb>parseFloat(Qb)){Pb=String(Sb);break a}}Pb=Qb}Tb=Pb;Ub={};_.Vb=function(a){return _.Eb(Ub,a,function(){return 0<=_.fb(Tb,a)})};
if(_.m.document&&_.Gb){var Xb=Ob();Wb=Xb?Xb:parseInt(Tb,10)||void 0}else Wb=void 0;var Yb=Wb;
var Zb=_.kb(),$b=xb()||_.v("iPod"),ac=_.v("iPad"),bc=_.v("Android")&&!(_.lb()||_.kb()||_.v("Opera")||_.v("Silk")),cc=_.lb(),dc=_.mb()&&!yb();
var ec={},fc=null;
_.w=function(){};_.gc="function"==typeof Uint8Array;
_.z=function(a,b,c,d,e){a.g=null;b||(b=c?[c]:[]);a.o=c?String(c):void 0;a.l=0===c?-1:0;a.K=b;a:{if(b=a.K.length)if(--b,c=a.K[b],!(null===c||"object"!=typeof c||Array.isArray(c)||_.gc&&c instanceof Uint8Array)){a.j=b-a.l;a.h=c;break a}a.j=Number.MAX_VALUE}a.D={};if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.l,a.K[c]=a.K[c]||_.hc):(_.ic(a),a.h[c]=a.h[c]||_.hc);if(e&&e.length)for(b=0;b<e.length;b++){c=d=void 0;for(var f=a,h=e[b],g=0;g<h.length;g++){var k=h[g],n=_.x(f,k);null!=n&&(c=k,d=n,_.y(f,k,void 0))}c&&
_.y(f,c,d)}};_.hc=[];_.ic=function(a){var b=a.j+a.l;a.K[b]||(a.h=a.K[b]={})};_.x=function(a,b){if(b<a.j){b+=a.l;var c=a.K[b];return c===_.hc?a.K[b]=[]:c}if(a.h)return c=a.h[b],c===_.hc?a.h[b]=[]:c};_.A=function(a,b){a=_.x(a,b);return null==a?a:!!a};_.jc=function(a,b,c){a=_.x(a,b);return null==a?c:a};_.y=function(a,b,c){b<a.j?a.K[b+a.l]=c:(_.ic(a),a.h[b]=c);return a};_.B=function(a,b,c){a.g||(a.g={});if(!a.g[c]){var d=_.x(a,c);d&&(a.g[c]=new b(d))}return a.g[c]};
_.C=function(a,b,c){a.g||(a.g={});var d=c?c.K:c;a.g[b]=c;return _.y(a,b,d)};
_.w.prototype.m=_.gc?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){var b;void 0===b&&(b=0);if(!fc){fc={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));ec[e]=f;for(var h=0;h<f.length;h++){var g=f[h];void 0===fc[g]&&(fc[g]=h)}}}b=ec[b];c=[];for(d=0;d<this.length;d+=3){var k=this[d],n=(e=d+1<this.length)?this[d+1]:0;g=(f=d+2<this.length)?this[d+2]:0;
h=k>>2;k=(k&3)<<4|n>>4;n=(n&15)<<2|g>>6;g&=63;f||(g=64,e||(n=64));c.push(b[h],b[k],b[n]||"",b[g]||"")}return c.join("")};try{return JSON.stringify(this.K&&this.K,kc)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.K&&this.K,kc)};var kc=function(a,b){return"number"!==typeof b||!isNaN(b)&&Infinity!==b&&-Infinity!==b?b:String(b)};_.w.prototype.toString=function(){return this.K.toString()};
_.D=function(){this.L=this.L;this.D=this.D};_.D.prototype.L=!1;_.D.prototype.fa=function(){this.L||(this.L=!0,this.C())};_.G=function(a,b){_.E(a,_.Ea(_.F,b))};_.E=function(a,b,c){a.L?void 0!==c?b.call(c):b():(a.D||(a.D=[]),a.D.push(void 0!==c?(0,_.q)(b,c):b))};_.D.prototype.C=function(){if(this.D)for(;this.D.length;)this.D.shift()()};_.F=function(a){a&&"function"==typeof a.fa&&a.fa()};
var lc=function(a,b){this.l=a;this.j=b;this.h=0;this.g=null};lc.prototype.get=function(){if(0<this.h){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.l();return a};var mc=function(a,b){a.j(b);100>a.h&&(a.h++,b.next=a.g,a.g=b)};
var qc;_.nc=[];_.oc=[];_.pc=!1;qc=function(a){_.nc[_.nc.length]=a;if(_.pc)for(var b=0;b<_.oc.length;b++)a((0,_.q)(_.oc[b].h,_.oc[b]))};
var rc=!_.Ib&&!_.Gb||_.Gb&&9<=Number(Yb)||_.Ib&&_.Vb("1.9.1");
var uc;_.tc=function(a,b){var c=b||document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.sc(c,"*",a,b)[0]||null}return a||null};
_.sc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.Oa(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.vc=function(a,b){_.Ua(b,function(c,d){c&&"object"==typeof c&&c.Ia&&(c=c.Fa());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:uc.hasOwnProperty(d)?a.setAttribute(uc[d],c):_.ab(d,"aria-")||_.ab(d,"data-")?a.setAttribute(d,c):a[d]=c})};uc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.wc=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};_.xc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.yc=function(a){this.g=a||_.m.document||document};_.yc.prototype.F=function(a){return"string"===typeof a?this.g.getElementById(a):a};_.yc.prototype.setProperties=_.vc;_.zc=function(a,b){return _.wc(a.g,b)};
_.yc.prototype.getChildren=function(a){return rc&&void 0!=a.children?a.children:(0,_.Ja)(a.childNodes,function(b){return 1==b.nodeType})};_.yc.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var Ac,Cc,Dc,Bc;Ac=function(a){_.m.setTimeout(function(){throw a;},0)};_.Ec=function(a,b){var c=a;b&&(c=(0,_.q)(a,b));c=Bc(c);!za(_.m.setImmediate)||_.m.Window&&_.m.Window.prototype&&!_.v("Edge")&&_.m.Window.prototype.setImmediate==_.m.setImmediate?(Cc||(Cc=Dc()),Cc(c)):_.m.setImmediate(c)};
Dc=function(){var a=_.m.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.v("Presto")&&(a=function(){var e=_.wc(document,"IFRAME");e.style.display="none";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.close();var h="callImmediate"+Math.random(),g="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=(0,_.q)(function(k){if(("*"==g||k.origin==g)&&k.data==h)this.port1.onmessage()},
this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(h,g)}}});if("undefined"!==typeof a&&!_.jb()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.wb;c.wb=null;e()}};return function(e){d.next={wb:e};d=d.next;b.port2.postMessage(0)}}return function(e){_.m.setTimeout(e,0)}};Bc=function(a){return a};qc(function(a){Bc=a});
var Fc=function(){this.h=this.g=null},Hc=new lc(function(){return new Gc},function(a){a.reset()});Fc.prototype.add=function(a,b){var c=Hc.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};Fc.prototype.remove=function(){var a=null;this.g&&(a=this.g,this.g=this.g.next,this.g||(this.h=null),a.next=null);return a};var Gc=function(){this.next=this.h=this.g=null};Gc.prototype.set=function(a,b){this.g=a;this.h=b;this.next=null};Gc.prototype.reset=function(){this.next=this.h=this.g=null};
var Mc=function(a,b){Ic||Jc();Kc||(Ic(),Kc=!0);Lc.add(a,b)},Ic,Jc=function(){if(_.m.Promise&&_.m.Promise.resolve){var a=_.m.Promise.resolve(void 0);Ic=function(){a.then(Nc)}}else Ic=function(){_.Ec(Nc)}},Kc=!1,Lc=new Fc,Nc=function(){for(var a;a=Lc.remove();){try{a.g.call(a.h)}catch(b){Ac(b)}mc(Hc,a)}Kc=!1};
var Oc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
var Rc,Sc,Tc,Yc,bd,cd,ad,Zc;_.Qc=function(a){this.g=0;this.o=void 0;this.j=this.h=this.l=null;this.m=this.D=!1;if(a!=_.wa)try{var b=this;a.call(void 0,function(c){_.Pc(b,2,c)},function(c){_.Pc(b,3,c)})}catch(c){_.Pc(this,3,c)}};Rc=function(){this.next=this.j=this.h=this.m=this.g=null;this.l=!1};Rc.prototype.reset=function(){this.j=this.h=this.m=this.g=null;this.l=!1};Sc=new lc(function(){return new Rc},function(a){a.reset()});Tc=function(a,b,c){var d=Sc.get();d.m=a;d.h=b;d.j=c;return d};
_.Vc=function(){var a,b=new _.Qc(function(c){a=c});return new Uc(b,a)};_.Qc.prototype.then=function(a,b,c){return _.Wc(this,za(a)?a:null,za(b)?b:null,c)};_.Qc.prototype.$goog_Thenable=!0;_.Qc.prototype.cancel=function(a){if(0==this.g){var b=new Xc(a);Mc(function(){Yc(this,b)},this)}};
Yc=function(a,b){if(0==a.g)if(a.l){var c=a.l;if(c.h){for(var d=0,e=null,f=null,h=c.h;h&&(h.l||(d++,h.g==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.g&&1==d?Yc(c,b):(f?(d=f,d.next==c.j&&(c.j=d),d.next=d.next.next):Zc(c),$c(c,e,3,b)))}a.l=null}else _.Pc(a,3,b)};bd=function(a,b){a.h||2!=a.g&&3!=a.g||ad(a);a.j?a.j.next=b:a.h=b;a.j=b};
_.Wc=function(a,b,c,d){var e=Tc(null,null,null);e.g=new _.Qc(function(f,h){e.m=b?function(g){try{var k=b.call(d,g);f(k)}catch(n){h(n)}}:f;e.h=c?function(g){try{var k=c.call(d,g);void 0===k&&g instanceof Xc?h(g):f(k)}catch(n){h(n)}}:h});e.g.l=a;bd(a,e);return e.g};_.Qc.prototype.A=function(a){this.g=0;_.Pc(this,2,a)};_.Qc.prototype.H=function(a){this.g=0;_.Pc(this,3,a)};
_.Pc=function(a,b,c){if(0==a.g){a===c&&(b=3,c=new TypeError("k"));a.g=1;a:{var d=c,e=a.A,f=a.H;if(d instanceof _.Qc){bd(d,Tc(e||_.wa,f||null,a));var h=!0}else if(Oc(d))d.then(e,f,a),h=!0;else{if(_.ua(d))try{var g=d.then;if(za(g)){cd(d,g,e,f,a);h=!0;break a}}catch(k){f.call(a,k);h=!0;break a}h=!1}}h||(a.o=c,a.g=b,a.l=null,ad(a),3!=b||c instanceof Xc||dd(a,c))}};cd=function(a,b,c,d,e){var f=!1,h=function(k){f||(f=!0,c.call(e,k))},g=function(k){f||(f=!0,d.call(e,k))};try{b.call(a,h,g)}catch(k){g(k)}};
ad=function(a){a.D||(a.D=!0,Mc(a.v,a))};Zc=function(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);return b};_.Qc.prototype.v=function(){for(var a;a=Zc(this);)$c(this,a,this.g,this.o);this.D=!1};
var $c=function(a,b,c,d){if(3==c&&b.h&&!b.l)for(;a&&a.m;a=a.l)a.m=!1;if(b.g)b.g.l=null,ed(b,c,d);else try{b.l?b.m.call(b.j):ed(b,c,d)}catch(e){fd.call(null,e)}mc(Sc,b)},ed=function(a,b,c){2==b?a.m.call(a.j,c):a.h&&a.h.call(a.j,c)},dd=function(a,b){a.m=!0;Mc(function(){a.m&&fd.call(null,b)})},fd=Ac,Xc=function(a){_.Ha.call(this,a)};_.r(Xc,_.Ha);Xc.prototype.name="cancel";var Uc=function(a,b){this.g=a;this.h=b};
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.gd=function(a){this.v=[];this.J=a;this.D=this.j=!1;this.m=void 0;this.I=this.N=this.H=!1;this.A=0;this.g=null;this.o=0};_.gd.prototype.cancel=function(a){if(this.j)this.m instanceof _.gd&&this.m.cancel();else{if(this.g){var b=this.g;delete this.g;a?b.cancel(a):(b.o--,0>=b.o&&b.cancel())}this.J?this.J.call(null,this):this.I=!0;this.j||this.G(new _.hd(this))}};_.gd.prototype.B=function(a,b){this.H=!1;id(this,a,b)};
var id=function(a,b,c){a.j=!0;a.m=c;a.D=!b;jd(a)},ld=function(a){if(a.j){if(!a.I)throw new kd(a);a.I=!1}};_.gd.prototype.l=function(a){ld(this);id(this,!0,a)};_.gd.prototype.G=function(a){ld(this);id(this,!1,a)};_.nd=function(a,b,c){_.md(a,b,null,c)};_.md=function(a,b,c,d){a.v.push([b,c,d]);a.j&&jd(a)};_.gd.prototype.then=function(a,b,c){var d,e,f=new _.Qc(function(h,g){d=h;e=g});_.md(this,d,function(h){h instanceof _.hd?f.cancel():e(h)});return f.then(a,b,c)};_.gd.prototype.$goog_Thenable=!0;
_.gd.prototype.h=function(a){var b=new _.gd;_.md(this,b.l,b.G,b);a&&(b.g=this,this.o++);return b};_.gd.prototype.isError=function(a){return a instanceof Error};
var od=function(a){return(0,_.La)(a.v,function(b){return za(b[1])})},jd=function(a){if(a.A&&a.j&&od(a)){var b=a.A,c=pd[b];c&&(_.m.clearTimeout(c.g),delete pd[b]);a.A=0}a.g&&(a.g.o--,delete a.g);b=a.m;for(var d=c=!1;a.v.length&&!a.H;){var e=a.v.shift(),f=e[0],h=e[1];e=e[2];if(f=a.D?h:f)try{var g=f.call(e||null,b);void 0!==g&&(a.D=a.D&&(g==b||a.isError(g)),a.m=b=g);if(Oc(b)||"function"===typeof _.m.Promise&&b instanceof _.m.Promise)d=!0,a.H=!0}catch(k){b=k,a.D=!0,od(a)||(c=!0)}}a.m=b;d&&(g=(0,_.q)(a.B,
a,!0),d=(0,_.q)(a.B,a,!1),b instanceof _.gd?(_.md(b,g,d),b.N=!0):b.then(g,d));c&&(b=new qd(b),pd[b.g]=b,a.A=b.g)},kd=function(){_.Ha.call(this)};_.r(kd,_.Ha);kd.prototype.message="Deferred has already fired";kd.prototype.name="AlreadyCalledError";_.hd=function(){_.Ha.call(this)};_.r(_.hd,_.Ha);_.hd.prototype.message="Deferred was canceled";_.hd.prototype.name="CanceledError";var qd=function(a){this.g=_.m.setTimeout((0,_.q)(this.l,this),0);this.h=a};
qd.prototype.l=function(){delete pd[this.g];throw this.h;};var pd={};
var sd,rd,vd,wd,ud;_.td=function(a){var b=[];rd(new sd,a,b);return b.join("")};sd=function(){};
rd=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(Array.isArray(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),rd(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),ud(d,c),c.push(":"),rd(a,f,c),e=","));c.push("}");return}}switch(typeof b){case "string":ud(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("l`"+typeof b);}}};vd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};wd=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;ud=function(a,b){b.push('"',a.replace(wd,function(c){var d=vd[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),vd[c]=d);return d}),'"')};
var xd="StopIteration"in _.m?_.m.StopIteration:{message:"StopIteration",stack:""},yd=function(){};yd.prototype.next=function(){throw xd;};yd.prototype.oa=function(){return this};
var zd=function(a){if(a instanceof yd)return a;if("function"==typeof a.oa)return a.oa(!1);if(_.ya(a)){var b=0,c=new yd;c.next=function(){for(;;){if(b>=a.length)throw xd;if(b in a)return a[b++];b++}};return c}throw Error("m");},Ad=function(a,b){if(_.ya(a))try{(0,_.u)(a,b,void 0)}catch(c){if(c!==xd)throw c;}else{a=zd(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==xd)throw c;}}},Bd=function(a){if(_.ya(a))return _.Ta(a);a=zd(a);var b=[];Ad(a,function(c){b.push(c)});return b};
_.H=function(a,b){this.h={};this.g=[];this.j=this.l=0;var c=arguments.length;if(1<c){if(c%2)throw Error("i");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof _.H)for(c=a.ca(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};_.H.prototype.X=function(){Cd(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};_.H.prototype.ca=function(){Cd(this);return this.g.concat()};_.Ed=function(a,b){return Dd(a.h,b)};
_.H.prototype.clear=function(){this.h={};this.j=this.l=this.g.length=0};_.H.prototype.remove=function(a){return Dd(this.h,a)?(delete this.h[a],this.l--,this.j++,this.g.length>2*this.l&&Cd(this),!0):!1};var Cd=function(a){if(a.l!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];Dd(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.l!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],Dd(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}};_.H.prototype.get=function(a,b){return Dd(this.h,a)?this.h[a]:b};
_.H.prototype.set=function(a,b){Dd(this.h,a)||(this.l++,this.g.push(a),this.j++);this.h[a]=b};_.H.prototype.forEach=function(a,b){for(var c=this.ca(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.H.prototype.oa=function(a){Cd(this);var b=0,c=this.j,d=this,e=new yd;e.next=function(){if(c!=d.j)throw Error("n");if(b>=d.g.length)throw xd;var f=d.g[b++];return a?f:d.h[f]};return e};var Dd=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
_.I=function(a,b){this.type="undefined"!=typeof _.Fd&&a instanceof _.Fd?String(a):a;this.g=this.target=b;this.defaultPrevented=this.h=!1};_.I.prototype.j=function(){this.h=!0};_.I.prototype.l=function(){this.defaultPrevented=!0};
var Gd=!_.Gb||9<=Number(Yb),Hd=_.Gb&&!_.Vb("9"),Id=function(){if(!_.m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{_.m.addEventListener("test",_.wa,b),_.m.removeEventListener("test",_.wa,b)}catch(c){}return a}();
var Kd=function(a,b){_.I.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.ba=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;if(b=a.relatedTarget){if(_.Ib){a:{try{Db(b.nodeName);var e=
!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";
this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Jd[a.pointerType]||"";this.state=a.state;this.ba=a;a.defaultPrevented&&this.l()}};_.r(Kd,_.I);var Jd={2:"touch",3:"pen",4:"mouse"};Kd.prototype.j=function(){Kd.P.j.call(this);this.ba.stopPropagation?this.ba.stopPropagation():this.ba.cancelBubble=!0};
Kd.prototype.l=function(){Kd.P.l.call(this);var a=this.ba;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Hd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var Ld,Nd;Ld="closure_listenable_"+(1E6*Math.random()|0);_.Md=function(a){return!(!a||!a[Ld])};Nd=0;
var Od=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.Sa=e;this.key=++Nd;this.removed=this.Pa=!1},Pd=function(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.Sa=null};
var Qd=function(a){this.src=a;this.g={};this.h=0},Ud,Rd;Qd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var h=Rd(a,b,d,e);-1<h?(b=a[h],c||(b.Pa=!1)):(b=new Od(b,this.src,f,!!d,e),b.Pa=c,a.push(b));return b};Qd.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.g))return!1;var e=this.g[a];b=Rd(e,b,c,d);return-1<b?(Pd(e[b]),_.Pa(e,b),0==e.length&&(delete this.g[a],this.h--),!0):!1};
var Sd=function(a,b){var c=b.type;c in a.g&&_.Ra(a.g[c],b)&&(Pd(b),0==a.g[c].length&&(delete a.g[c],a.h--))};Qd.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.g)if(!a||c==a){for(var d=this.g[c],e=0;e<d.length;e++)++b,Pd(d[e]);delete this.g[c];this.h--}return b};_.Td=function(a,b,c,d,e){a=a.g[b.toString()];b=-1;a&&(b=Rd(a,c,d,e));return-1<b?a[b]:null};Ud=function(a){return Va(a.g,function(b){for(;0<b.length;)return!0;return!1})};
Rd=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.Sa==d)return e}return-1};
var Vd,Wd,Xd,ae,ce,de,ie,he,ee,je;Vd="closure_lm_"+(1E6*Math.random()|0);Wd={};Xd=0;_.Zd=function(a,b,c,d,e){if(d&&d.once)return _.Yd(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)_.Zd(a,b[f],c,d,e);return null}c=_.$d(c);return _.Md(a)?a.listen(b,c,_.ua(d)?!!d.capture:!!d,e):ae(a,b,c,!1,d,e)};
ae=function(a,b,c,d,e,f){if(!b)throw Error("o");var h=_.ua(e)?!!e.capture:!!e,g=_.be(a);g||(a[Vd]=g=new Qd(a));c=g.add(b,c,d,h,f);if(c.proxy)return c;d=ce();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Id||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(de(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("p");Xd++;return c};
ce=function(){var a=ee,b=Gd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};_.Yd=function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)_.Yd(a,b[f],c,d,e);return null}c=_.$d(c);return _.Md(a)?a.H(b,c,_.ua(d)?!!d.capture:!!d,e):ae(a,b,c,!0,d,e)};
_.fe=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)_.fe(a,b[f],c,d,e);else d=_.ua(d)?!!d.capture:!!d,c=_.$d(c),_.Md(a)?a.l.remove(String(b),c,d,e):a&&(a=_.be(a))&&(b=_.Td(a,b,c,d,e))&&_.ge(b)};
_.ge=function(a){if("number"!==typeof a&&a&&!a.removed){var b=a.src;if(_.Md(b))Sd(b.l,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(de(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Xd--;(c=_.be(b))?(Sd(c,a),0==c.h&&(c.src=null,b[Vd]=null)):Pd(a)}}};de=function(a){return a in Wd?Wd[a]:Wd[a]="on"+a};
ie=function(a,b,c,d){var e=!0;if(a=_.be(a))if(b=a.g[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.removed&&(f=he(f,d),e=e&&!1!==f)}return e};he=function(a,b){var c=a.listener,d=a.Sa||a.src;a.Pa&&_.ge(a);return c.call(d,b)};
ee=function(a,b){if(a.removed)return!0;if(!Gd){var c=b||_.va("window.event");b=new Kd(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.g;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.h&&0<=e;e--){b.g=c[e];var f=ie(c[e],a,!0,b);d=d&&f}for(e=0;!b.h&&e<c.length;e++)b.g=c[e],f=ie(c[e],a,!1,b),d=d&&f}return d}return he(a,new Kd(b,this))};
_.be=function(a){a=a[Vd];return a instanceof Qd?a:null};je="__closure_events_fn_"+(1E9*Math.random()>>>0);_.$d=function(a){if(za(a))return a;a[je]||(a[je]=function(b){return a.handleEvent(b)});return a[je]};qc(function(a){ee=a(ee)});
_.J=function(){_.D.call(this);this.l=new Qd(this);this.ja=this;this.I=null};_.r(_.J,_.D);_.J.prototype[Ld]=!0;_.J.prototype.addEventListener=function(a,b,c,d){_.Zd(this,a,b,c,d)};_.J.prototype.removeEventListener=function(a,b,c,d){_.fe(this,a,b,c,d)};
_.K=function(a,b){var c,d=a.I;if(d)for(c=[];d;d=d.I)c.push(d);a=a.ja;d=b.type||b;if("string"===typeof b)b=new _.I(b,a);else if(b instanceof _.I)b.target=b.target||a;else{var e=b;b=new _.I(d,a);_.Ya(b,e)}e=!0;if(c)for(var f=c.length-1;!b.h&&0<=f;f--){var h=b.g=c[f];e=h.sa(d,!0,b)&&e}b.h||(h=b.g=a,e=h.sa(d,!0,b)&&e,b.h||(e=h.sa(d,!1,b)&&e));if(c)for(f=0;!b.h&&f<c.length;f++)h=b.g=c[f],e=h.sa(d,!1,b)&&e;return e};_.J.prototype.C=function(){_.J.P.C.call(this);this.l&&this.l.removeAll(void 0);this.I=null};
_.J.prototype.listen=function(a,b,c,d){return this.l.add(String(a),b,!1,c,d)};_.J.prototype.H=function(a,b,c,d){return this.l.add(String(a),b,!0,c,d)};_.J.prototype.sa=function(a,b,c){a=this.l.g[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.capture==b){var h=f.listener,g=f.Sa||f.src;f.Pa&&Sd(this.l,f);d=!1!==h.call(g,c)&&d}}return d&&!c.defaultPrevented};
var ke=function(){};ke.prototype.g=null;var me=function(a){var b;(b=a.g)||(b={},le(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b};
var ne,oe=function(){};_.r(oe,ke);var pe=function(a){return(a=le(a))?new ActiveXObject(a):new XMLHttpRequest},le=function(a){if(!a.h&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.h=d}catch(e){}}throw Error("q");}return a.h};ne=new oe;
var re;_.qe=function(a){if(a.X&&"function"==typeof a.X)return a.X();if("string"===typeof a)return a.split("");if(_.ya(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b};
re=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);else if(_.ya(a)||"string"===typeof a)(0,_.u)(a,b,void 0);else{if(a.ca&&"function"==typeof a.ca)var c=a.ca();else if(a.X&&"function"==typeof a.X)c=void 0;else if(_.ya(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else for(e in c=[],d=0,a)c[d++]=e;d=_.qe(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}};
_.se=function(a,b){_.J.call(this);this.h=a||1;this.g=b||_.m;this.j=(0,_.q)(this.nc,this);this.m=(0,_.ta)()};_.r(_.se,_.J);_.l=_.se.prototype;_.l.ua=!1;_.l.da=null;_.l.setInterval=function(a){this.h=a;this.da&&this.ua?(this.stop(),this.start()):this.da&&this.stop()};_.l.nc=function(){if(this.ua){var a=(0,_.ta)()-this.m;0<a&&a<.8*this.h?this.da=this.g.setTimeout(this.j,this.h-a):(this.da&&(this.g.clearTimeout(this.da),this.da=null),_.K(this,"tick"),this.ua&&(this.stop(),this.start()))}};
_.l.start=function(){this.ua=!0;this.da||(this.da=this.g.setTimeout(this.j,this.h),this.m=(0,_.ta)())};_.l.stop=function(){this.ua=!1;this.da&&(this.g.clearTimeout(this.da),this.da=null)};_.l.C=function(){_.se.P.C.call(this);this.stop();delete this.g};_.te=function(a,b,c){if(za(a))c&&(a=(0,_.q)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.q)(a.handleEvent,a);else throw Error("r");return 2147483647<Number(b)?-1:_.m.setTimeout(a,b||0)};_.ue=function(a){_.m.clearTimeout(a)};
var ve=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,we=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};
var xe=function(a){_.J.call(this);this.headers=new _.H;this.B=a||null;this.h=!1;this.A=this.g=null;this.N="";this.j=this.J=this.m=this.G=!1;this.v=0;this.o=null;this.aa="";this.S=this.U=!1},ye,ze,Ae,Ie,He,Ee,Je;_.r(xe,_.J);ye=/^https?$/i;ze=["POST","PUT"];Ae=[];_.Be=function(a,b,c,d,e,f,h){var g=new xe;Ae.push(g);b&&g.listen("complete",b);g.H("ready",g.na);f&&(g.v=Math.max(0,f));h&&(g.U=h);g.send(a,c,d,e)};xe.prototype.na=function(){this.fa();_.Ra(Ae,this)};
xe.prototype.send=function(a,b,c,d){if(this.g)throw Error("s`"+this.N+"`"+a);b=b?b.toUpperCase():"GET";this.N=a;this.G=!1;this.h=!0;this.g=this.B?pe(this.B):pe(ne);this.A=this.B?me(this.B):me(ne);this.g.onreadystatechange=(0,_.q)(this.Z,this);try{this.J=!0,this.g.open(b,String(a),!0),this.J=!1}catch(f){Ce(this);return}a=c||"";var e=new _.H(this.headers);d&&re(d,function(f,h){e.set(h,f)});d=_.Na(e.ca(),De);c=_.m.FormData&&a instanceof _.m.FormData;!_.Oa(ze,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
e.forEach(function(f,h){this.g.setRequestHeader(h,f)},this);this.aa&&(this.g.responseType=this.aa);"withCredentials"in this.g&&this.g.withCredentials!==this.U&&(this.g.withCredentials=this.U);try{Ee(this),0<this.v&&((this.S=Fe(this.g))?(this.g.timeout=this.v,this.g.ontimeout=(0,_.q)(this.V,this)):this.o=_.te(this.V,this.v,this)),this.m=!0,this.g.send(a),this.m=!1}catch(f){Ce(this)}};
var Fe=function(a){return _.Gb&&_.Vb(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},De=function(a){return"content-type"==a.toLowerCase()};xe.prototype.V=function(){"undefined"!=typeof _.ra&&this.g&&(_.K(this,"timeout"),this.abort(8))};var Ce=function(a){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);Ge(a);He(a)},Ge=function(a){a.G||(a.G=!0,_.K(a,"complete"),_.K(a,"error"))};
xe.prototype.abort=function(){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,_.K(this,"complete"),_.K(this,"abort"),He(this))};xe.prototype.C=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),He(this,!0));xe.P.C.call(this)};xe.prototype.Z=function(){this.L||(this.J||this.m||this.j?Ie(this):this.R())};xe.prototype.R=function(){Ie(this)};
Ie=function(a){if(a.h&&"undefined"!=typeof _.ra&&(!a.A[1]||4!=(a.g?a.g.readyState:0)||2!=Je(a)))if(a.m&&4==(a.g?a.g.readyState:0))_.te(a.Z,0,a);else if(_.K(a,"readystatechange"),4==(a.g?a.g.readyState:0)){a.h=!1;try{_.Ke(a)?(_.K(a,"complete"),_.K(a,"success")):Ge(a)}finally{He(a)}}};He=function(a,b){if(a.g){Ee(a);var c=a.g,d=a.A[0]?_.wa:null;a.g=null;a.A=null;b||_.K(a,"ready");try{c.onreadystatechange=d}catch(e){}}};Ee=function(a){a.g&&a.S&&(a.g.ontimeout=null);a.o&&(_.ue(a.o),a.o=null)};
_.Ke=function(a){var b=Je(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.N).match(ve)[1]||null,!a&&_.m.self&&_.m.self.location&&(a=_.m.self.location.protocol,a=a.substr(0,a.length-1)),b=!ye.test(a?a.toLowerCase():"");c=b}return c};Je=function(a){try{return 2<(a.g?a.g.readyState:0)?a.g.status:-1}catch(b){return-1}};qc(function(a){xe.prototype.R=a(xe.prototype.R)});
var Me;_.M=function(a){_.D.call(this);this.U=a;this.H={}};_.r(_.M,_.D);var Le=[];_.M.prototype.listen=function(a,b,c,d){Array.isArray(b)||(b&&(Le[0]=b.toString()),b=Le);for(var e=0;e<b.length;e++){var f=_.Zd(a,b[e],c||this.handleEvent,d||!1,this.U||this);if(!f)break;this.H[f.key]=f}return this};_.Ne=function(a,b,c,d){Me(a,b,c,d,void 0)};Me=function(a,b,c,d,e,f){if(Array.isArray(c))for(var h=0;h<c.length;h++)Me(a,b,c[h],d,e,f);else(b=_.Yd(b,c,d||a.handleEvent,e,f||a.U||a))&&(a.H[b.key]=b)};
_.M.prototype.removeAll=function(){_.Ua(this.H,function(a,b){this.H.hasOwnProperty(b)&&_.ge(a)},this);this.H={}};_.M.prototype.C=function(){_.M.P.C.call(this);this.removeAll()};_.M.prototype.handleEvent=function(){throw Error("t");};
_.Oe=function(a){_.z(this,a,0,null,null)};_.r(_.Oe,_.w);
var Qe=function(a,b){var c=Array.prototype.slice.call(arguments),d=c.shift();if("undefined"==typeof d)throw Error("u");return d.replace(/%([0\- \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(e,f,h,g,k,n,t,L){if("%"==n)return"%";var X=c.shift();if("undefined"==typeof X)throw Error("v");arguments[0]=X;return Pe[n].apply(null,arguments)})},Pe={s:function(a,b,c){return isNaN(c)||""==c||a.length>=Number(c)?a:a=-1<b.indexOf("-",0)?a+vb(" ",Number(c)-a.length):vb(" ",Number(c)-a.length)+a},f:function(a,b,c,
d,e){d=a.toString();isNaN(e)||""==e||(d=parseFloat(a).toFixed(e));var f=0>Number(a)?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=Number(a)&&(d=f+d);if(isNaN(c)||d.length>=Number(c))return d;d=isNaN(e)?Math.abs(Number(a)).toString():Math.abs(Number(a)).toFixed(e);a=Number(c)-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+vb(" ",a):f+vb(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,h,g){return Pe.f(parseInt(a,10),b,c,d,0,f,h,g)}};Pe.i=Pe.d;Pe.u=Pe.d;
_.N=function(a,b){for(var c=[],d=0;d<arguments.length;d++)if(arguments[d]instanceof Error)c.push(arguments[d].stack);else if("object"==typeof arguments[d])try{c.push(JSON.stringify(arguments[d]))}catch(e){c.push("_error_("+e+")")}else c.push(arguments[d]);window.console&&(d=new Date,d=Qe("%02d-%02d ",d.getMonth()+1,d.getDate())+d.toLocaleTimeString(void 0,{hour12:!1})+Qe(".%03d",d.getMilliseconds()),window.console.log(d+" info: "+Qe.apply({},c)))};
_.Se=function(a){_.z(this,a,"h_exts",Re,null)};_.r(_.Se,_.w);var Re=[2];_.Se.messageId="h_exts";
var Te,Ue,We,Ze,af,kf,bf,df,cf,gf,ef,$e,lf;_.O=function(a,b){this.h=this.o=this.m="";this.j=null;this.v=this.g="";this.D=!1;var c;a instanceof _.O?(this.D=void 0!==b?b:a.D,Te(this,a.m),this.o=a.o,this.h=a.h,Ue(this,a.j),this.g=a.g,We(this,Xe(a.l)),_.Ye(this,a.v)):a&&(c=String(a).match(ve))?(this.D=!!b,Te(this,c[1]||"",!0),this.o=Ze(c[2]||""),this.h=Ze(c[3]||"",!0),Ue(this,c[4]),this.g=Ze(c[5]||"",!0),We(this,c[6]||"",!0),_.Ye(this,c[7]||"",!0)):(this.D=!!b,this.l=new $e(null,this.D))};
_.O.prototype.toString=function(){var a=[],b=this.m;b&&a.push(af(b,bf,!0),":");var c=this.h;if(c||"file"==b)a.push("//"),(b=this.o)&&a.push(af(b,bf,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.j,null!=c&&a.push(":",String(c));if(c=this.g)this.h&&"/"!=c.charAt(0)&&a.push("/"),a.push(af(c,"/"==c.charAt(0)?cf:df,!0));(c=this.l.toString())&&a.push("?",c);(c=this.v)&&a.push("#",af(c,ef));return a.join("")};
Te=function(a,b,c){a.m=c?Ze(b,!0):b;a.m&&(a.m=a.m.replace(/:$/,""))};Ue=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("w`"+b);a.j=b}else a.j=null};We=function(a,b,c){b instanceof $e?(a.l=b,ff(a.l,a.D)):(c||(b=af(b,gf)),a.l=new $e(b,a.D))};_.P=function(a,b,c){a.l.set(b,c)};_.Ye=function(a,b,c){a.v=c?Ze(b):b};_.hf=function(a){return a instanceof _.O?new _.O(a):new _.O(a,void 0)};
_.jf=function(a,b){a instanceof _.O||(a=_.hf(a));b instanceof _.O||(b=_.hf(b));var c=a;a=new _.O(c);var d=!!b.m;d?Te(a,b.m):d=!!b.o;d?a.o=b.o:d=!!b.h;d?a.h=b.h:d=null!=b.j;var e=b.g;if(d)Ue(a,b.j);else if(d=!!b.g)if("/"!=e.charAt(0)&&(c.h&&!c.g?e="/"+e:(c=a.g.lastIndexOf("/"),-1!=c&&(e=a.g.substr(0,c+1)+e))),".."==e||"."==e)e="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){c=_.ab(e,"/");e=e.split("/");for(var f=[],h=0;h<e.length;){var g=e[h++];"."==g?c&&h==e.length&&f.push(""):".."==g?((1<f.length||
1==f.length&&""!=f[0])&&f.pop(),c&&h==e.length&&f.push("")):(f.push(g),c=!0)}e=f.join("/")}d?a.g=e:d=""!==b.l.toString();d?We(a,Xe(b.l)):d=!!b.v;d&&_.Ye(a,b.v);return a};Ze=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""};af=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,kf),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};kf=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};bf=/[#\/\?@]/g;df=/[#\?:]/g;
cf=/[#\?]/g;gf=/[#\?@]/g;ef=/#/g;$e=function(a,b){this.h=this.g=null;this.l=a||null;this.j=!!b};lf=function(a){a.g||(a.g=new _.H,a.h=0,a.l&&we(a.l,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};$e.prototype.add=function(a,b){lf(this);this.l=null;a=mf(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};$e.prototype.remove=function(a){lf(this);a=mf(this,a);return _.Ed(this.g,a)?(this.l=null,this.h-=this.g.get(a).length,this.g.remove(a)):!1};
$e.prototype.clear=function(){this.g=this.l=null;this.h=0};var nf=function(a,b){lf(a);b=mf(a,b);return _.Ed(a.g,b)};_.l=$e.prototype;_.l.forEach=function(a,b){lf(this);this.g.forEach(function(c,d){(0,_.u)(c,function(e){a.call(b,e,d,this)},this)},this)};_.l.ca=function(){lf(this);for(var a=this.g.X(),b=this.g.ca(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
_.l.X=function(a){lf(this);var b=[];if("string"===typeof a)nf(this,a)&&(b=_.Sa(b,this.g.get(mf(this,a))));else{a=this.g.X();for(var c=0;c<a.length;c++)b=_.Sa(b,a[c])}return b};_.l.set=function(a,b){lf(this);this.l=null;a=mf(this,a);nf(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};_.l.get=function(a,b){if(!a)return b;a=this.X(a);return 0<a.length?String(a[0]):b};_.of=function(a,b,c){a.remove(b);0<c.length&&(a.l=null,a.g.set(mf(a,b),_.Ta(c)),a.h+=c.length)};
$e.prototype.toString=function(){if(this.l)return this.l;if(!this.g)return"";for(var a=[],b=this.g.ca(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.X(d);for(var f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}}return this.l=a.join("&")};
var Xe=function(a){var b=new $e;b.l=a.l;a.g&&(b.g=new _.H(a.g),b.h=a.h);return b},mf=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},ff=function(a,b){b&&!a.j&&(lf(a),a.l=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(this.remove(d),_.of(this,e,c))},a));a.j=b};
var pf;pf=function(a){return(a=a.exec(_.gb))?a[1]:""};_.qf=function(){if(Zb)return pf(/Firefox\/([0-9.]+)/);if(_.Gb||Hb||Fb)return Tb;if(cc)return yb()?pf(/CriOS\/([0-9.]+)/):pf(/Chrome\/([0-9.]+)/);if(dc&&!yb())return pf(/Version\/([0-9.]+)/);if($b||ac){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.gb);if(a)return a[1]+"."+a[2]}else if(bc)return(a=pf(/Android\s+([0-9.]+)/))?a:pf(/Version\/([0-9.]+)/);return""}();
var rf=function(a,b){_.I.call(this,a,b);this.$=b};_.p(rf,_.I);
var sf=function(a){_.z(this,a,0,null,null)};_.r(sf,_.w);var tf=function(a,b){return _.y(a,1,b)};
var uf=function(a){_.z(this,a,"capi_md1571",null,null)};_.r(uf,_.w);uf.messageId="capi_md1571";var vf=function(a,b){return _.y(a,1,b)},wf=function(a,b){return _.y(a,2,b)},xf=function(a,b){return _.y(a,3,b)};
var zf=function(){for(var a=10,b=yf,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},yf="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
_.Af=function(a,b){_.D.call(this);this.o=b||zf();this.j=this.g="";this.h=this.l=null;this.v=a;this.m=new _.M(this);_.G(this,this.m);this.m.listen(window,"message",this.A)};_.r(_.Af,_.D);_.Af.prototype.ka=function(a,b,c){this.j=a;this.l=b;this.h=c};
_.Af.prototype.A=function(a){a=a.ba;var b=a.origin;this.l&&this.l!=a.source||"*"!=this.j&&this.j!=b?b=!1:this.h?(b=(new _.O(b)).h,b=_.bb(b,this.h)?b.length==this.h.length||"."==this.h[0]||"."==b[b.length-1-this.h.length]:!1):b=!0;if(b&&(b=a.data)&&"string"===typeof b&&"["==b[0]){try{var c=JSON.parse(b);if(!Array.isArray(c))return}catch(d){return}if(0!=c.length&&"capi_md1571"==c[0]&&(c=new uf(c),_.x(c,1)==this.o)){b=_.x(c,3);if(!this.g)this.g=b;else if(this.g!=b)return;"*"!=this.j&&this.l||this.ka(a.origin,
a.source);1==_.x(c,2)?this.send(2):this.v(c,a)}}};_.Af.prototype.send=function(a,b,c){if(this.g&&this.l){a=wf(vf(xf(b||new uf,this.o),this.g),a);var d=JSON.stringify(a.K),e=this.l,f=this.j;_.Gb?_.te(function(){e.postMessage(d,f)}):c?e.postMessage(d,f,c):e.postMessage(d,f)}};
var Bf=function(a,b,c,d){this.l=_.Vc();this.g=new _.Af((0,_.q)(this.m,this),c);this.g.ka("*",a,d);this.g.g=b;this.h=new _.se(50);this.h.start();_.Zd(this.h,"tick",this.j,!1,this);this.j();a=this.l.g;b=this.D;b=Tc(b,b,this);b.l=!0;bd(a,b)};Bf.prototype.D=function(){_.F(this.g);_.fe(this.h,"tick",this.j,!1,this);_.F(this.h)};Bf.prototype.j=function(){this.g.send(1)};Bf.prototype.m=function(a,b){2==_.x(a,2)&&this.l.h(b.origin)};
var Cf=function(a,b,c){_.D.call(this);this.h=a;a=_.x(b,3);b=_.x(b,1);this.g=new _.Af((0,_.q)(this.l,this),b);this.g.g=a;c&&this.g.ka(c.origin,c.source);_.G(this,this.g)};_.r(Cf,_.D);Cf.prototype.send=function(a){var b=new uf;a=_.C(b,4,a);this.g.send(0,a)};Cf.prototype.connect=function(a,b){this.g.ka(a,b);this.g.send(3)};Cf.prototype.l=function(a){0==_.x(a,2)&&(a=_.B(a,sf,4),this.h(a))};Cf.prototype.j=_.wa;
var Ef=function(a,b,c){_.D.call(this);this.m=a;this.h=this.g=this.l=null;c?(this.h=c.ports[0],Df(this)):(this.g=new _.Af(_.wa,_.x(b,1)),a=_.x(b,3),this.g.g=a)};_.p(Ef,_.D);Ef.prototype.C=function(){_.D.prototype.C.call(this);this.h&&this.h.close();_.F(this.g)};Ef.prototype.j=function(){this.l=new _.M(this);_.G(this,this.l);Df(this)};Ef.prototype.send=function(a){this.h.postMessage(a.K)};
Ef.prototype.connect=function(a,b){var c=new MessageChannel;this.h=c.port1;Df(this);var d=this.g;this.g=null;c=c.port2;d.ka(a,b);d.send(4,void 0,[c]);_.F(d)};var Df=function(a){a.h&&a.l&&(a.l.listen(a.h,"message",a.o),a.h.start())};Ef.prototype.o=function(a){a=a.ba;try{var b=new sf(a.data)}catch(c){return}this.m(b)};
var Ff=function(a,b,c){var d=!1;void 0!==_.x(b,2)?4==_.x(b,2)&&(d=!0):d=cc;return d?new Ef(a,b,c):new Cf(a,b,c)};
var Kf,Mf;_.Gf=function(){_.J.call(this);this.o=null;this.v=!1;this.m=[];this.j=[];_.E(this,this.B,this);this.h=null};_.p(_.Gf,_.J);_.Gf.prototype.B=function(){for(;this.j.length;)this.j.shift()()};_.If=function(a){a.B();a.m=[];a.h=new _.gd;a.j.push((0,_.q)(a.h.cancel,a.h));a.v=!1;_.nd(a.h.h(),function(b){(Ud(this.l)||this.I)&&_.Hf(this);this.j.push(_.Ea(_.F,b))},a)};_.Gf.prototype.sendMessage=function(a){Jf(this,a.K)};var Jf=function(a,b){if(a.h){var c=tf(new sf,b);_.nd(a.h.h(),function(d){d.send(c)})}};
_.Gf.prototype.M=function(){return this};_.Gf.prototype.ka=function(a,b,c){this.g.ka(a,b,c)};_.Lf=function(a,b,c,d){_.If(a);Kf(a,b,c,d).then(function(e){var f=xf(vf(new uf,e.oc),c);f=Ff((0,_.q)(this.A,this),f);f.connect(e.origin,b);this.h.l(f)},void 0,a)};Kf=function(a,b,c,d){var e=zf();b=(new Bf(b,c,e,d)).l.g;a.j.push((0,_.q)(b.cancel,b));return b.then(function(f){return{oc:e,origin:f}})};
_.Gf.prototype.J=function(a,b){if(3==_.x(a,2)||4==_.x(a,2))_.F(this.g),this.g=null,this.h.l(Ff((0,_.q)(this.A,this),a,b))};_.Gf.prototype.A=function(a){this.m.push(a);this.G()};_.Gf.prototype.G=function(){for(;Mf(this););};Mf=function(a){if(a.L||!a.v||0==a.m.length)return!1;var b=_.x(a.m.shift(),1);a.o&&Jf(a.o,b);_.K(a,new rf(b[0],b));return!0};_.Hf=function(a){a.v||(a.v=!0,a.h&&_.nd(a.h.h(),function(b){b.j();_.te(this.G,0,this)},a))};
_.Gf.prototype.listen=function(a,b,c,d){_.Hf(this);return _.J.prototype.listen.call(this,a,b,c,d)};_.Gf.prototype.H=function(a,b,c,d){_.Hf(this);return _.J.prototype.H.call(this,a,b,c,d)};
var Nf=function(a){this.h=a;this.j="empty";this.g=null;this.l={}};Nf.prototype.ia=function(a){this.j=a;return this};Nf.prototype.va=function(a){this.g=a;return this};Nf.prototype.sb=function(a){this.l=_.Wa(a);return this};
var Of=function(){};
var Pf=function(){};_.r(Pf,Of);Pf.prototype.clear=function(){var a=Bd(this.oa(!0)),b=this;(0,_.u)(a,function(c){b.remove(c)})};
var Qf=function(a){this.g=a};_.r(Qf,Pf);_.l=Qf.prototype;_.l.isAvailable=function(){if(!this.g)return!1;try{return this.g.setItem("__sak","1"),this.g.removeItem("__sak"),!0}catch(a){return!1}};_.l.set=function(a,b){try{this.g.setItem(a,b)}catch(c){if(0==this.g.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};_.l.get=function(a){a=this.g.getItem(a);if("string"!==typeof a&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};
_.l.remove=function(a){this.g.removeItem(a)};_.l.oa=function(a){var b=0,c=this.g,d=new yd;d.next=function(){if(b>=c.length)throw xd;var e=c.key(b++);if(a)return e;e=c.getItem(e);if("string"!==typeof e)throw"Storage mechanism: Invalid value was encountered";return e};return d};_.l.clear=function(){this.g.clear()};_.l.key=function(a){return this.g.key(a)};
var Rf=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.g=a};_.r(Rf,Qf);
var Tf=function(a,b){this.l=a;this.g=[];this.h=null;b&&(this.h=new Rf);if(null!=this.h&&this.h.isAvailable()&&(a=this.h.get("__webmonitoring_RateThrottler_history_hourlyRate"),null!=a))try{this.g=JSON.parse(a)||[]}catch(c){}a=!1;Array.isArray(this.g)||(this.g=[],a=!0);for(;this.g.length>this.l;)this.g.shift(),a=!0;a&&Sf(this)},Sf=function(a){if(null!=a.h&&a.h.isAvailable())try{a.h.set("__webmonitoring_RateThrottler_history_hourlyRate",_.td(a.g))}catch(b){}};
var Uf=function(a){_.D.call(this);this.g=a;this.m=!1};_.r(Uf,_.D);Uf.prototype.setEnabled=function(a){this.m=a};
var Q=function(a){Uf.call(this,a);this.H=100;this.A={};this.W=null;this.l="";this.I=!0;this.o=10;this.h=null;this.j=!1};_.p(Q,Uf);_.l=Q.prototype;_.l.Fb=function(a){this.I=a;return this};_.l.mc=function(a){this.o=Math.min(a,100);return this};_.l.Db=function(a){this.H=a;return this};_.l.ub=function(a,b){this.A[a]=b;return this};_.l.Cb=function(a){this.W=a;return this};_.l.lc=function(a){this.l=a;return this};
_.l.enable=function(){if(this.m)return!1;this.v=window.onerror;window.onerror=this.cc.bind(this);this.setEnabled(!0);return!0};
_.l.Ab=function(a,b,c,d,e,f){f=void 0===f?new Map:f;var h=_.hf(window.location.href);a=null!=e&&null!=e.message?e.message:a;var g;if(g="function"!==typeof this.W||this.W(h.g,a,b,c,d,e))if(g=this.j){g=Object.keys(this.A);for(var k=100,n=0;n<g.length;++n){var t=g[n];(new RegExp(t)).test(a)&&(k=this.A[t])}if(g=(100*Math.random()).toFixed(6)>=this.H*k/100?!1:!0){0<=this.o&&null===this.h&&(this.h=new Tf(this.o,this.I));if(null===this.h)g=!1;else{a:{g=this.h;k=(0,_.ta)();if(g.g.length==g.l)if(g.g[0]<k-
36E5)g.g.shift();else{g=!1;break a}g.g.push(k);Sf(g);g=!0}g=!g}g=!g&&this.j}}g&&(e=e||null,b=Vf(this,h,a,f,b,c,void 0!==d?d:null),b.prod=this.g.h,b.ver=this.g.j,c=null!==e?_.wb(e.stack):"",b=Wf(b),_.cb(a)||(d=c.split("\n"),-1<d[0].indexOf(a)&&(d.splice(0,1),c=d.join("\n"))),Xf(this,"https://clients2.google.com/cr/staging_report",b,c),h={product:this.g.h,url:h.g,js_errors_count:"1"},a=_.wb(this.g.g),_.cb(a)||(h.version=a),Xf(this,"https://clients2.google.com/cr/staging_perf",Wf(h)))};
_.l.cc=function(a,b,c,d,e){this.Ab(a,b,c,d,e);null!=this.v&&"function"===typeof this.v&&this.v(a,b,c,d,e)};
var Vf=function(a,b,c,d,e,f,h){var g=_.Wa(a.g.l);d.forEach(function(k,n){g[n]=k});g.url=b.g;g.type="JavascriptError";g.error_message=c;g.browser=Yf();g.browser_version=_.qf;g.os=_.Bb()?"Chrome OS":_.v("Linux")?"Linux":_.Ab()?"Windows":_.v("Android")?"Android":xb()?"iPhone":_.v("iPad")?"iPad":_.v("iPod")?"iPod":_.zb()?"Mac":"Unknown";g.os_version=Cb();b=a.g.g;null!==b&&(g.channel=b);_.cb(a.l)||(g.guid=a.l);null!==e&&(g.src=e);null!==f&&(g.line=f.toString());null!==h&&(g.column=h.toString());return g},
Wf=function(a){var b="",c;for(c in a)b+=_.cb(b)?"?":"&",b+=c+"="+encodeURIComponent(a[c]);return b},Xf=function(a,b,c,d){d=d||"";var e=_.cb(d)?{}:{"Content-Type":"text/plain"};_.Be(b+c,a.B.bind(a,b),"POST",d,e,6E4,!0)};Q.prototype.B=function(a,b){_.Ke(b.target)};var Yf=function(){var a="Other";Fb?a="Opera":_.Gb?a="Internet Explorer":Zb?a="Firefox":cc?a="Chrome":dc&&(a="Safari");return a};Q.prototype.reportError=Q.prototype.Ab;Q.prototype.enable=Q.prototype.enable;Q.prototype.setClientId=Q.prototype.lc;
Q.prototype.setCallback=Q.prototype.Cb;Q.prototype.addPerErrorMessageSampling=Q.prototype.ub;Q.prototype.setGlobalSampling=Q.prototype.Db;Q.prototype.setMaxErrorsPerHour=Q.prototype.mc;Q.prototype.setUseLocalStorage=Q.prototype.Fb;
var Zf=function(a){Uf.call(this,a);this.W=null;this.h=0};_.r(Zf,Uf);Zf.prototype.Cb=function(a){this.W=a;return this};var $f=[{age:6E4,name:"1m"},{age:15E5,name:"25m"},{age:36E5,name:"1h"},{age:36E6,name:"10h"}];Zf.prototype.enable=function(){if(this.m)return!1;if(window.performance&&window.performance.memory){var a=new _.se(6E4);_.G(this,a);var b=new _.M(this);_.G(this,b);b.listen(a,"tick",this.l);a.start();this.setEnabled(!0);return!0}return!1};
Zf.prototype.l=function(){this.h+=6E4;for(var a="",b=0;b<$f.length;++b)if(this.h==$f[b].age){a=$f[b].name;break}if(""!=a){b=ag.test(_.gb)?"":"32_bit_";var c=window.performance.memory;if(c.totalJSHeapSize&&c.usedJSHeapSize){a=[{name:"total_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Total JS heap (MB)",value:Math.round(c.totalJSHeapSize/1048576)},{name:"used_"+b+"js_heap_size_mb_"+a+"_raw",displayName:"Used JS heap (MB)",value:Math.round(c.usedJSHeapSize/1048576)}];b=_.hf(window.location.href).g;
c="?product="+encodeURIComponent(this.g.h)+"&url="+encodeURIComponent(b);var d=_.wb(this.g.g);_.cb(d)||(c+="&version="+encodeURIComponent(d));for(d=0;d<a.length;++d)c+="&"+encodeURIComponent(a[d].name)+"="+a[d].value,"function"===typeof this.W&&this.W(b,a[d].displayName,a[d].value);_.Be("https://clients2.google.com/cr/staging_perf"+c,bg,"POST","",null,6E4,!0)}}};var bg=function(a){_.Ke(a.target)},ag=/(x86_64|Win64)/;
var R=function(a){_.D.call(this);this.h=new Nf(a);this.g={}};_.r(R,_.D);_.Fa("webmonitoring.Monitoring",R);R.prototype.ia=function(a){this.h.ia(a);return this};R.prototype.setVersion=R.prototype.ia;R.prototype.va=function(a){this.h.va(a);return this};R.prototype.setChannel=R.prototype.va;R.prototype.sb=function(a){this.h.sb(a);return this};R.prototype.setContext=R.prototype.sb;R.prototype.Ra=function(){null==this.g[2]&&(this.g[2]=new Q(this.h));return this.g[2]};
R.prototype.createJsErrorsReporter=R.prototype.Ra;
var cg=function(a){R.call(this,a)};_.p(cg,R);cg.prototype.ia=function(a){return R.prototype.ia.call(this,a)};cg.prototype.va=function(a){return R.prototype.va.call(this,a)};cg.prototype.Ra=function(){var a=R.prototype.Ra.call(this);a.j=!0;return a};
_.dg=function(){var a=new cg("Google_Hangouts_Chrome");a.va(chrome.runtime.id);a.ia(chrome.runtime.getManifest().version);null==a.g[1]&&(a.g[1]=new Zf(a.h));a.g[1].enable();a.Ra().Fb(!1).Db(100).ub("Script error.",0).enable()};

}catch(e){_._DumpException(e)}
try{
var bq=function(a,b){_.Wc(a,null,b,void 0)},cq=function(a){_.z(this,a,"uv_r_hrd",null,null)};_.r(cq,_.w);cq.messageId="uv_r_hrd";
var dq=function(a,b){return a.l.get(b)},eq=function(a,b){a.o=b;_.E(a,function(){this.o=null},a);_.Hf(a)},fq=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.ya(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},gq=function(a){for(var b={},c=0,d=0;d<a.length;){var e=a[d++];var f=e;f=_.ua(f)?"o"+_.Ba(f):(typeof f).charAt(0)+f;Object.prototype.hasOwnProperty.call(b,f)||(b[f]=!0,a[c++]=e)}a.length=c},hq=function(a,b,c){a=_.A(a,b);
return null==a?c:a},iq=function(a){var b=new _.Gf;_.If(b);b.g=new _.Af((0,_.q)(b.J,b),a);b.g.ka("*",void 0,void 0);b.j.push(_.Ea(_.F,b.g));return b},jq=function(a){this.g=a;_.Gb||(delete this.g.lpu,delete this.g.ppu)},kq=function(a,b){var c={};c.cn=Math.floor(2147483648*Math.random()).toString(36);c.tp=1;c.ifrid=b;c.pu=a;return new jq(c)},lq=["cn","tp"];_.Fa("GTalk_IFrameChannelConfig.build",kq);
var mq=function(){},pq=function(a){var b=a.ra,c=function(k){c.P.constructor.call(this,k);var n=this.ea.length;this.g=[];for(var t=0;t<n;++t)this.ea[t].Mc||(this.g[t]=new this.ea[t](k))};_.r(c,b);for(var d=[];a&&a!==Object;){if(b=a.ra){b.ea&&(fq(d,b.ea),gq(d));var e=b.prototype,f;for(f in e)if(e.hasOwnProperty(f)&&"function"===typeof e[f]&&e[f]!==b){var h=!!e[f].Hb,g=nq(f,e,d,h);(h=oq(f,e,g,h))&&(c.prototype[f]=h)}}a=a===Object?Object:Object.getPrototypeOf?Object.getPrototypeOf(a.prototype).constructor||
Object:a.P&&a.P.constructor||Object}c.prototype.ea=d;return c},nq=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e},oq=function(a,b,c,d){var e;c.length?d?e=function(f){var h=this.g[c[0]];return h?h[a].apply(this.g[c[0]],arguments):this.ea[c[0]].prototype[a].apply(this,arguments)}:b[a].Jb?e=function(f){a:{var h=Array.prototype.slice.call(arguments,0);for(var g=0;g<c.length;++g){var k=this.g[c[g]];if(k=k?k[a].apply(k,h):this.ea[c[g]].prototype[a].apply(this,
h)){h=k;break a}}h=!1}return h}:b[a].Ib?e=function(f){a:{var h=Array.prototype.slice.call(arguments,0);for(var g=0;g<c.length;++g){var k=this.g[c[g]];k=k?k[a].apply(k,h):this.ea[c[g]].prototype[a].apply(this,h);if(null!=k){h=k;break a}}h=void 0}return h}:b[a].Yb?e=function(f){for(var h=Array.prototype.slice.call(arguments,0),g=0;g<c.length;++g){var k=this.g[c[g]];k?k[a].apply(k,h):this.ea[c[g]].prototype[a].apply(this,h)}}:e=function(f){for(var h=Array.prototype.slice.call(arguments,0),g=[],k=0;k<
c.length;++k){var n=this.g[c[k]];g.push(n?n[a].apply(n,h):this.ea[c[k]].prototype[a].apply(this,h))}return g}:d||b[a].Jb||b[a].Ib||b[a].Yb?e=null:e=qq;return e},qq=function(){return[]};mq.prototype.m=function(a){if(this.g)for(var b=0;b<this.g.length;++b)if(this.g[b]instanceof a)return this.g[b];return null};var rq=function(a){(a?a:function(){}).Hb=!0};
var sq=function(){};_.r(sq,mq);sq.prototype.h=function(a){return a};rq(sq.prototype.h);sq.prototype.l=function(){return!0};rq(sq.prototype.l);
var tq=function(a){_.z(this,a,0,null,null)};_.r(tq,_.w);
var uq=function(a,b){var c=new tq;b=_.y(c,1,b);return _.y(b,2,a)},vq=uq("?",0),wq=uq("q",1),xq=uq("<",2),yq=uq(">",3),zq=uq("~",4),Aq=uq("s",5),Bq={sc:vq,Ac:wq,uc:xq,vc:yq,tc:zq,Bc:Aq};
var Cq=function(a){_.z(this,a,"ci:ec",null,null)};_.r(Cq,_.w);Cq.messageId="ci:ec";
var Dq=function(a){_.z(this,a,"h_cc",null,null)};_.r(Dq,_.w);var Eq=function(a){_.z(this,a,0,null,null)};_.r(Eq,_.w);var Fq=function(a){_.z(this,a,0,null,null)};_.r(Fq,_.w);var Gq=function(a){_.z(this,a,0,null,null)};_.r(Gq,_.w);var Hq=function(a){_.z(this,a,0,null,null)};_.r(Hq,_.w);Dq.messageId="h_cc";var Iq=function(a,b){_.y(a,3,b)},Jq=function(a,b){_.y(a,4,b)},Kq=function(a,b){_.y(a,11,b)};
var Lq=function(a){return this.kb.m(a)};
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Mq=function(){this.g=window.document||{cookie:""}};_.l=Mq.prototype;
_.l.set=function(a,b,c){var d=!1;if("object"===typeof c){var e=c.Oc;d=c.secure||!1;var f=c.domain||void 0;var h=c.path||void 0;var g=c.Tb}if(/[;=\s]/.test(a))throw Error("K`"+a);if(/[;\r\n]/.test(b))throw Error("L`"+b);void 0===g&&(g=-1);c=f?";domain="+f:"";h=h?";path="+h:"";d=d?";secure":"";g=0>g?"":0==g?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,_.ta)()+1E3*g)).toUTCString();this.g.cookie=a+"="+b+c+h+g+d+(null!=e?";samesite="+e:"")};
_.l.get=function(a,b){for(var c=a+"=",d=(this.g.cookie||"").split(";"),e=0,f;e<d.length;e++){f=(0,_.db)(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.l.remove=function(a,b,c){var d=void 0!==this.get(a);this.set(a,"",{Tb:0,path:b,domain:c});return d};_.l.ca=function(){return Nq(this).keys};_.l.X=function(){return Nq(this).values};_.l.clear=function(){for(var a=Nq(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
var Nq=function(a){a=(a.g.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=(0,_.db)(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
var Oq=function(a,b){if(!this.kb){for(var c=this.constructor;c&&!c.ra;)c=c.P&&c.P.constructor;c.ra.yb||(c.ra.yb=pq(c));this.kb=new c.ra.yb(this);this.m||(this.m=Lq)}var d=this.kb.h(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(_.ab(d,"https://talkgadget.google.com/talkgadget/")){c=(new Mq).get("WCSDBG","");c=c.split(";")[0];c=c.split("|")[0];var e=["plus.google.com"],f=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<c.length&&!_.Oa(e,c)&&f.test(c)&&(d=_.hf(d),d=_.hf("https://"+
c+d.g).toString())}this.l=d;this.j=b||new Cq;a.notificationsOnly&&_.y(this.j,1,!0);this.h="0";null!=a.authUser?this.h=a.authUser:(b=dq(new _.O(window.location.href),"authuser"),null!=b&&(this.h=b));this.H=a.clientUrl||"notifierclient";b=dq(_.hf(this.H),"authuser");null!=b&&(this.h=b);this.ib=a.propertyName||"Google Talk";this.B=a.cssUrl;this.locale=a.locale;this.o=a.debug;this.Oa=a.userJid;this.Ma=a.uiVersion;this.Rb=null!=a.rosterExpanded?a.rosterExpanded:!0;this.ja=a.hostLogMinValue;this.Ca=a.hideChat;
this.Mb=a.refresh;this.U=a.hideProfileCard;this.aa=a.hideStatusMsgs;this.Z=a.hideRosterOptions;this.V=a.hideRecentConversations;this.S=a.hideOTR;this.lb=a.hostServerMessageCallback||!1;this.xa=a.isCentralRoster;this.nb=a.isFullFrame||!1;this.Qb=a.rosterClass||"talk_roster";this.Sb=a.rosterId||"talk_roster";this.g="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.g=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.Ba=a.parentToken;void 0!==a.isRtl||
_.$a.test(this.locale);this.v=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var h in Bq)b.push(Bq[h].K)}this.J=a.entityId;this.Ka=a.useQuasarPanels||!1;this.silent=a.silent||!1;this.mb=a.ignoreCentralRoster||!1;this.Pb=a.lazy||!1;this.jb=a.handleProfileLinks||!1;this.na=a.hostSettings;this.A=a.screen;this.G=a.docsConfig;this.Nb=a.jsmode;this.Aa=a.moleWidth;this.za=a.moleHeight;this.ya=a.minimizedMoleHeight||36;this.Xb=a.derp;this.La=window.location.protocol+"//"+window.location.host;this.D="";
this.R=a.optOutAllowed;this.N=a.legacyTalkSignedIn;this.Na=a.useSpareMole;this.I=a.conversationId};sq.P||_.r(sq,mq);Oq.ra=sq;
var Qq=function(a){var b={},c=_.jc(a,1,"hangouts.google.com"),d="";0>c.indexOf("://")&&(d="https://",0<=c.indexOf(":")&&23!=_.x(a,2)&&27!=_.x(a,2)&&(d="http://"));b.clientBaseUrl=d+c+"/webchat/u/"+_.jc(a,8,"0")+"/";b.clientUrl="load";b.authUser=_.jc(a,8,"0");b.propertyName=Pq(_.x(a,2));b.locale=_.x(a,4);b.hideProfileCard=!0;b.parentToken=_.x(a,3);b.isRtl=hq(a,6,!1);b.lazy=hq(a,7,!1);b.entityId=_.x(a,9);b.hostSettings=_.x(a,5);b.jsmode=_.x(a,11);b.isFullFrame=hq(a,13,!1);b.rosterId=_.jc(a,12,"talk_roster");
b.rosterIframeId=_.jc(a,12,"talk_roster");b.rosterIframeIdB=_.jc(a,15,"gtn-roster-iframe-id-b");b.derp=!!hq(a,16,!1);c=_.B(a,Hq,14);null!=c&&(b.isCentralRoster=hq(c,1,!1),b.useQuasarPanels=hq(c,2,!1));c=_.B(a,Eq,10);null!=c&&(b.moleManagerLeftMargin=_.x(c,1),b.moleManagerMiddleMargin=_.x(c,2),b.moleManagerRightMargin=_.x(c,3),b.moleManagerNoMoleAreaMargin=_.x(c,4),b.moleManagerBoundingElementId=_.x(c,5),b.moleWidth=_.x(c,6),b.moleHeight=_.x(c,7),b.minimizedMoleHeight=_.x(c,8));c=_.B(a,Fq,18);null!=
c&&(b.optOutAllowed=hq(c,1,!0),d=_.B(c,Gq,3),null!=d&&(b.legacyTalkSignedIn=hq(d,1,!0)),c=_.A(c,4),null!=c&&(b.useSpareMole=c));b.uiVersion=2;b.hideStatusMsgs=!0;b.hideRecentConversations=!0;c=new Cq;c=_.y(c,2,!0);c=_.y(c,1,!0);c=_.y(c,3,!1);b.endpointConfig=c;b.ignoreAutomatedRoster=hq(a,17,!1);b.conversationId=_.x(a,19);return b},Pq=function(a){switch(a){case 1:return"homepage";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";
case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 36:return"StartPage"}},Rq=function(a,b){if(-1!=a.indexOf("talkgadget.")){var c=_.hf(a),d=c.g;if(0<=d.indexOf("/u/"))return a;a=d.lastIndexOf("_/");if(0>a||a!=d.length-2)d+="_/";c.g="/u/"+b+d;return c.toString()}return a};
var Sq=function(a,b,c,d,e){_.D.call(this);this.g=a;this.h=d||window.document;this.l=new _.M(this);_.G(this,this.l);var f=_.gb;d=new _.O(a.l+a.H);hq(a.j,2,!1)||(_.P(d,"ts","0"),_.P(d,"re",a.Rb),_.P(d,"ref",a.Mb));_.P(d,"client","sm");_.P(d,"prop",a.ib);_.P(d,"nav","true");_.P(d,"fid",a.g);a.o&&_.P(d,"debug",a.o);_.P(d,"os",_.Kb);_.P(d,"stime",c);a.Ca&&_.P(d,"hc",a.Ca);for(c=0;c<lq.length;++c);b=_.td(b.g);_.P(d,"xpc",b);_.P(d,"ec",_.td(a.j.K));a.A&&_.P(d,"screen",a.A);-1!=f.indexOf("MSIE")&&_.P(d,"ua",
f);a.Ba&&_.P(d,"pvt",a.Ba);a.lb&&_.P(d,"hsmc","true");void 0!==a.ja&&_.P(d,"logl",a.ja);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),_.P(d,"href",b.join("?")));b=new _.O(window.location.href);"false"==dq(b,"uacheck")&&_.P(d,"uacheck",!1);(f=a.Nb)&&_.P(d,"jsmode",f);(f=dq(b,"cssmode"))&&_.P(d,"cssmode",f);(f=dq(b,"convid"))&&_.P(d,"convid",f);if(f=b.l.X("convp"))Array.isArray(f)||(f=[String(f)]),_.of(d.l,"convp",f);(f=dq(b,"smexp"))&&
_.P(d,"smexp",f);f=b.l.X("mods");a.Pb&&f.push("lazy");e&&(f=_.Sa(f,e));0<f.length&&_.P(d,"mods",f.join(","));if(!a.l||0>a.l.indexOf("/u/"))(e=dq(b,"authuser"))?_.P(d,"authuser",e):null!=a.h&&_.P(d,"authuser",a.h);e=dq(b,"eid");_.cb(_.wb(e))||_.P(d,"eid",e);_.cb(_.wb(this.g.J))||_.P(d,"eid",this.g.J);null!=this.g.v&&_.P(d,"pos",this.g.v);void 0!==a.Ma&&_.P(d,"uiv",this.g.Ma);a.B&&_.P(d,"css",a.B);e=a.locale||dq(b,"hl");null!=e&&_.P(d,"hl",e);void 0!==a.Oa&&_.P(d,"uj",a.Oa);null!=a.U&&_.P(d,"hpc",a.U);
null!=a.aa&&_.P(d,"hsm",a.aa);null!=a.Z&&_.P(d,"hro",a.Z);null!=a.V&&_.P(d,"hrc",a.V);null!=a.S&&_.P(d,"hotr",a.S);null!=a.xa&&_.P(d,"pop",a.xa);_.P(d,"pal","1");null!=a.Ka&&_.P(d,"uqp",a.Ka);null!=a.R&&_.P(d,"gooa",a.R);null!=a.N&&_.P(d,"gltsi",a.N);null!=a.Na&&_.P(d,"gusm",a.Na);null!=a.silent&&_.P(d,"sl",a.silent);a.mb&&_.P(d,"icr","1");a.jb&&_.P(d,"hpl","1");a.na&&_.P(d,"hs",a.na);a.G&&_.P(d,"dc",_.td(a.G.K));null!=a.Aa&&_.P(d,"molew",a.Aa);null!=a.za&&_.P(d,"moleh",a.za);null!=a.ya&&_.P(d,"mmoleh",
a.ya);a.Xb&&_.P(d,"derp","1");a.D&&_.P(d,"fcho",a.D);null!=a.La&&_.P(d,"two",a.La);null!=a.I&&_.P(d,"convid",a.I);_.P(d,"host","1");_.P(d,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.ta)()).toString(36));this.j=d.toString()};_.p(Sq,_.D);Sq.prototype.install=function(a,b){Tq(this,a,b,_.wa)};
var Tq=function(a,b,c,d){var e=a.h.getElementById(b);e||(e=a.h.createElement("div"),e.id=b,e.className=a.g.Qb,a.h.body.appendChild(e));a=(0,_.q)(function(){var f="";this.g.nb||(f="height:400px");var h=_.zc(new _.yc(this.h),"IFRAME");_.vc(h,{id:this.g.g,name:this.g.g,"class":"talk_iframe",frameborder:"0",style:f,"aria-hidden":"true",allow:"microphone *; autoplay *; microphone"});_.tc("talk_loading_msg",e)||_.xc(e);e.appendChild(h);var g=this.h.getElementById(this.g.g);_.Ne(this.l,g,["load","error"],
function(k){g.contentWindow.postMessage("AllowFrame: Chat","*");d(k)});g.src=this.j.toString();c()},a);window.setTimeout(a,0)};
var Uq=function(a){var b=_.jf(_.x(a,2),"/webchat/extension-start");_.x(a,5)&&_.P(b,"e",_.x(a,5));return new _.Qc(function(c,d){_.Be(b,function(e){_.Ke(e.target)||d();try{var f=e.target;try{var h=f.g?f.g.responseText:""}catch(k){h=""}var g=JSON.parse(h);c(new _.Se(g))}catch(k){d(k.message)}})})};
var Wq=function(){_.M.call(this);var a=this;_.N("Starting ...");this.listen(window,"unload",this.fa);this.h=new _.Oe(JSON.parse(decodeURI(location.hash.substr(1))));this.g=iq(_.x(this.h,1));_.G(this,this.g);this.l=new _.Gf;_.G(this,this.l);bq(Uq(this.h).then(function(b){return Vq(a,b)}),function(b){_.N("Failed to start : %s.",b||"")})},Xq;_.p(Wq,_.M);
var Vq=function(a,b){if(!a.L&&(a.g.sendMessage(b),_.x(b,1))){var c=new Dq,d=_.hf(_.x(a.h,2)),e=d.h;null!=d.j&&(e+=":"+d.j);_.y(c,1,e);_.y(c,2,23);_.y(c,13,!0);_.y(c,17,!0);Iq(c,_.x(b,1));Kq(c,_.x(a.h,4));Jq(c,_.x(a.h,3)||"en");b=Qq(c);var f=new Oq(b,b.endpointConfig);f.l=Rq(f.l,f.h);f.D=location.origin;f.g="gtn-roster-iframe-id-q";b=kq(f.l,f.g);b=new Sq(f,b,(0,_.ta)(),window.document);_.G(a,b);Tq(b,f.Sb,function(){},function(){_.Lf(a.l,document.getElementById(f.g).contentWindow,"31ACFC0_","google.com");
eq(a.l,a.g);eq(a.g,a.l);a.g.sendMessage(new cq)})}};_.Fa("default_host._DumpException",function(a){return console.error(a.stack)});_.dg();if(!Xq||Xq.L)Xq=new Wq;

}catch(e){_._DumpException(e)}
}).call(this,this.default_host);
// Google Inc.
