"use strict";this.default_windowbootstrap=this.default_windowbootstrap||{};(function(_){var window=this;
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa,ba,ca,da,ea,fa,ja,pa;aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};da=ca(this);ea=function(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};
ea("Symbol",function(a){if(a)return a;var b=function(e,f){this.g=e;ba(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.g};var c=0,d=function(e){if(this instanceof d)throw new TypeError("b");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("c");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});fa=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
_.ha=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}};_.ia="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};if("function"==typeof Object.setPrototypeOf)ja=Object.setPrototypeOf;else{var la;a:{var ma={a:!0},na={};try{na.__proto__=ma;la=na.a;break a}catch(a){}la=!1}ja=la?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("d`"+a);return a}:null}_.oa=ja;
pa=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
ea("WeakMap",function(a){function b(){}function c(k){var n=typeof k;return"object"===n&&null!==k||"function"===n}function d(k){if(!pa(k,f)){var n=new b;ba(k,f,{value:n})}}function e(k){var n=Object[k];n&&(Object[k]=function(t){if(t instanceof b)return t;Object.isExtensible(t)&&d(t);return n(t)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),n=Object.seal({}),t=new a([[k,2],[n,3]]);if(2!=t.get(k)||3!=t.get(n))return!1;t.delete(k);t.set(n,4);return!t.has(k)&&4==t.get(n)}catch(L){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var h=0,g=function(k){this.g=(h+=Math.random()+1).toString();if(k){k=_.ha(k);for(var n;!(n=k.next()).done;)n=n.value,this.set(n[0],n[1])}};g.prototype.set=function(k,n){if(!c(k))throw Error("g");d(k);if(!pa(k,f))throw Error("h`"+k);k[f][this.g]=n;return this};g.prototype.get=function(k){return c(k)&&pa(k,f)?k[f][this.g]:void 0};g.prototype.has=function(k){return c(k)&&pa(k,f)&&pa(k[f],this.g)};g.prototype.delete=function(k){return c(k)&&
pa(k,f)&&pa(k[f],this.g)?delete k[f][this.g]:!1};return g});
ea("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),k=new a(_.ha([[g,"s"]]));if("s"!=k.get(g)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var n=k.entries(),t=n.next();if(t.done||t.value[0]!=g||"s"!=t.value[1])return!1;t=n.next();return t.done||4!=t.value[0].x||"t"!=t.value[1]||!n.next().done?!1:!0}catch(L){return!1}}())return a;var b=new WeakMap,c=function(g){this.h={};this.g=
f();this.size=0;if(g){g=_.ha(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(g,k){g=0===g?0:g;var n=d(this,g);n.list||(n.list=this.h[n.id]=[]);n.entry?n.entry.value=k:(n.entry={next:this.g,previous:this.g.previous,head:this.g,key:g,value:k},n.list.push(n.entry),this.g.previous.next=n.entry,this.g.previous=n.entry,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.h[g.id],
g.entry.previous.next=g.entry.next,g.entry.next.previous=g.entry.previous,g.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.h={};this.g=this.g.previous=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).entry};c.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,
function(g){return g.value})};c.prototype.forEach=function(g,k){for(var n=this.entries(),t;!(t=n.next()).done;)t=t.value,g.call(k,t[1],t[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,k){var n=k&&typeof k;"object"==n||"function"==n?b.has(k)?n=b.get(k):(n=""+ ++h,b.set(k,n)):n="p_"+k;var t=g.h[n];if(t&&pa(g.h,n))for(g=0;g<t.length;g++){var L=t[g];if(k!==k&&L.key!==L.key||k===L.key)return{id:n,list:t,index:g,entry:L}}return{id:n,list:t,index:-1,entry:void 0}},e=function(g,
k){var n=g.g;return fa(function(){if(n){for(;n.head!=g.g;)n=n.previous;for(;n.next!=n.head;)return n=n.next,{done:!1,value:k(n)};n=null}return{done:!0,value:void 0}})},f=function(){var g={};return g.previous=g.next=g.head=g},h=0;return c});var qa=function(a,b){a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
ea("Array.prototype.keys",function(a){return a?a:function(){return qa(this,function(b){return b})}});ea("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});ea("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
ea("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("e`includes");if(b instanceof RegExp)throw new TypeError("f`includes");return-1!==this.indexOf(b,c||0)}});ea("Array.prototype.values",function(a){return a?a:function(){return qa(this,function(b,c){return c})}});_.ra=_.ra||{};_.m=this||self;_.sa="closure_uid_"+(1E9*Math.random()>>>0);_.ta=Date.now;

}catch(e){_._DumpException(e)}
try{
_.eg="https://support.google.com/chrome/answer/185277?hl="+chrome.i18n.getMessage("@@ui_locale");chrome.i18n.getMessage("@@ui_locale");_.fg="https://support.google.com/hangouts/answer/6127720?hl="+chrome.i18n.getMessage("@@ui_locale");

}catch(e){_._DumpException(e)}
try{
location.search&&window.addEventListener("load",function(){chrome.runtime.getBackgroundPage(function(a){a.__onExtWindowLoad(window)})});

}catch(e){_._DumpException(e)}
}).call(this,this.default_windowbootstrap);
// Google Inc.
